import type {Plugin} from 'vite'
import {readFileSync} from 'node:fs'
/** Local-only read fixture, explicitly opt-in. Never included in production builds. */
export function kazakhFixture():Plugin{const history=JSON.parse(readFileSync(new URL('../../demo/history-polished.json',import.meta.url),'utf8'));const knowledge=JSON.parse(readFileSync(new URL('../../demo/knowledge-approved.local.json',import.meta.url),'utf8'));return{name:'tekton-kz-local-fixture',enforce:'pre',apply:'serve',transform(code,id){if(process.env.TEKTON_KZ_FIXTURE!=='1'||!id.endsWith('/src/lib/data.ts'))return null;return {code:`
import {groundedAnswer} from '/supabase/functions/_shared/assistant-grounding.mjs';
import {historyRatings} from '/src/lib/history-rating.mjs';
const knowledge=${JSON.stringify(knowledge)};const history=${JSON.stringify(history)};
const now=new Date().toISOString();const actor={id:'synthetic-worker',email:'local@example.invalid',role:new URLSearchParams(location.search).get('role')||'worker',name:'Тест орындаушы'};
let orders=['issued','accepted','in_progress','completed','ai_review','closed','rework'].map((status,i)=>({id:124+i,status,version:1,kind:'unplanned',priority:i===0?'emergency':'normal',assignee_id:actor.id,assignee:actor.name,equipment_id:1,equipment:'Насос Н-12',section:'Учебный участок',title:'Учебный ремонт '+(i+1),created_at:now,closed_at:status==='closed'?now:null,deadline:new Date(Date.now()+3600000).toISOString(),before_photos:[],closure:{works:'Оригинальный текст ремонта не переводится',photos:[],materials:[],fault_code:'Г-01'},ai_result:{verdict:"needs_master_review",mode:"rules",reasons:[],score:null}}));
if(new URLSearchParams(location.search).get('photos')==='1'){orders.forEach(o=>{o.before_photos=['/tests/fixtures/photo-before.svg'];o.closure.photos=['/tests/fixtures/photo-after.svg']})}
if(new URLSearchParams(location.search).get('content')==='long'){orders.forEach(o=>{o.title='Аварийная проверка уплотнения, опорного подшипника и соединения кабельного ввода';o.equipment='Циркуляционный насос высокого давления НЦ-12 / привод линии подготовки сырья';o.priority='emergency'});}
if(new URLSearchParams(location.search).get('forecast')==='1'){for(let i=0;i<8;i++)orders.push({...orders[0],id:900+i,status:'closed',priority:'normal',created_at:new Date(Date.now()-(71-i*10)*86400000).toISOString(),title:'Синтетическая история прогноза '+(i+1)});}
if(new URLSearchParams(location.search).get('scored')==='1'){orders.find(o=>o.status==='closed').ai_result.human_score=4;}
if(new URLSearchParams(location.search).get('onework')==='1'){orders.find(o=>o.status==='rework').status='closed';}
if(new URLSearchParams(location.search).get('closedmany')==='1'){const closed=orders.find(x=>x.status==='closed');for(let i=0;i<65;i++)orders.push({...closed,id:500+i,title:'Учебный архив '+(i+1)});}
const historyOn=new URLSearchParams(location.search).get('history')==='1';
if(historyOn)orders=history.orders.map(o=>({...o,equipment_id:history.catalog.equipment.findIndex(e=>e.name===o.equipment)+1,assignee_id:history.catalog.workers.findIndex(w=>w.name===o.assignee)+100,version:1}));
const equipment=historyOn?history.catalog.equipment.map((e,i)=>({...e,id:i+1})):[{id:1,name:'Насос Н-12',section:'Учебный участок'}];
const employees=historyOn?[actor,...history.catalog.workers.map((w,i)=>({...w,id:i+100,role:'worker',on_shift:true,is_active:true}))]:[actor,{id:'synthetic-master',name:'Тест шебер',role:'master'}, {...actor,role:'worker',on_shift:true,is_active:true}];
export const supabase=null;export const state=async()=>({offline:new URLSearchParams(location.search).get('offline')==='1',cachedAt:Date.now(),actor,orders,employees,equipment,sections:historyOn?history.catalog.sections.map((name,i)=>({id:i+1,name})):[{id:1,name:'Учебный участок'}],events:[],notifications:[],permits:[],materials:[{id:1,name:'Учебное уплотнение',unit:'шт'}],fault_codes:[{code:'F01',name:'Учебная неисправность'}],work_norms:[]});
export const restoreSession=async()=>new URLSearchParams(location.search).get('role')!=='login';export const login=async()=>{};export const logout=async()=>{};
export const watch=()=>()=>{};export const watchNotifications=()=>()=>{};export const repairMemory=async()=>[];export const repeatTop=async()=>[];export const ratings=async(since,until)=>historyOn?historyRatings(orders,employees.filter(x=>x.role==='worker'),{since,until}):[];export const anomalies=async()=>[];export const refusalReviews=async()=>[];export const closedReportOrders=async()=>orders.filter(x=>x.status==='closed');export const knowledgeDocs=async()=>[];
export const reviewArchiveReceipt=()=>null;
export const assistantChat=async(message,orderId)=>{const o=orders.find(x=>x.id===orderId);return groundedAnswer({message,order:o?{...o,deadline_almaty:new Date(o.deadline).toLocaleString('ru',{timeZone:'Asia/Almaty'})}:null,docs:knowledge, memory:[],history:orders.filter(x=>x.status==='closed')})};
const noWrites=async()=>{throw new Error('Local read-only fixture: mutation blocked')};
export const createOrder=async x=>{if(new URLSearchParams(location.search).get('issuebench')!=='1')return noWrites();if(!x.title||!x.assignee_id)throw Error('Invalid synthetic issue');orders.push({...x,id:999,status:'issued',version:1,created_at:new Date().toISOString()});return{id:999,synthetic:true}};export const recordEquipmentState=noWrites;export const transition=noWrites,manageOrder=noWrites,reviewRefusal=noWrites,reviewRepairMemory=noWrites,reviewKnowledge=noWrites,submitKnowledge=noWrites,recordDeclarations=noWrites,recordIntakePhoto=noWrites,recordPermit=noWrites,startWork=noWrites,manualMasterDecision=noWrites;
export const telegramPairStatus=async()=>({enabled:false});export const beginTelegramPair=noWrites,confirmTelegramPair=noWrites,disconnectTelegramPair=noWrites;
`,map:null}}}}
