// Data-derived investigation signals, never a repair diagnosis or worker judgement.
const median=values=>{const a=[...values].sort((a,b)=>a-b);return a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2};
export function historySignals(orders,{since=-Infinity,until=Date.now()}={}){
 const rows=orders.filter(o=>!o.cancelled&&Number.isFinite(Date.parse(o.created_at))&&Date.parse(o.created_at)>=since&&Date.parse(o.created_at)<until);const signals=[];const byEquipment=new Map();
 for(const o of rows){const key=String(o.equipment_id??o.equipment);if(!byEquipment.has(key))byEquipment.set(key,[]);byEquipment.get(key).push(o)}
 const cohorts=new Map();for(const[key,list]of byEquipment){const sample=list[0];const family=String(sample.equipment??'').split(' ')[0];const cohort=String(sample.section??'')+':'+family;if(!cohorts.has(cohort))cohorts.set(cohort,[]);cohorts.get(cohort).push({key,list,unplanned:list.filter(o=>o.kind==='unplanned')})}
 for(const cohort of cohorts.values())if(cohort.length>=3)for(const entry of cohort){const peers=cohort.filter(x=>x!==entry).map(x=>x.unplanned.length);const baseline=median(peers);const ratio=baseline>0?entry.unplanned.length/baseline:null;if(ratio!==null&&ratio>=2.5&&entry.unplanned.length>=10){const codes={};for(const o of entry.unplanned){const c=o.fault_code??o.closure?.fault_code??'?';codes[c]=(codes[c]||0)+1}const top=Object.entries(codes).sort((a,b)=>b[1]-a[1])[0];signals.push({type:'repeat_concentration',equipment:entry.list[0].equipment,equipment_id:entry.key,count:entry.unplanned.length,peer_median:baseline,ratio,fault_code:top?.[0],fault_count:top?.[1],order_ids:entry.unplanned.map(o=>o.id),action:'Проверить причины повторов на узле; не диагноз'})}}
 for(const[key,list]of byEquipment){const pairs=[];for(const p of list.filter(o=>o.kind==='planned'&&o.status==='closed'&&Number.isFinite(Date.parse(o.closed_at)))){const following=list.filter(o=>o.kind==='unplanned'&&Date.parse(o.created_at)>Date.parse(p.closed_at)&&Date.parse(o.created_at)-Date.parse(p.closed_at)<=48*3600000);for(const u of following)pairs.push([p.id,u.id])}if(pairs.length>=3)signals.push({type:'post_planned',equipment:list[0].equipment,equipment_id:key,pairs,count:pairs.length,action:'Проверить связь внеплановых заявок с недавним обслуживанием; причина не установлена'})}
 const groups=new Map();for(const o of rows)for(const m of o.closure?.materials??[]){const q=Number(m.quantity);if(!Number.isFinite(q)||q<=0)continue;const key=String(o.section??'')+':'+String(o.equipment??'').split(' ')[0]+':'+(o.fault_code??o.closure?.fault_code)+':'+m.name+':'+m.unit;if(!groups.has(key))groups.set(key,[]);groups.get(key).push({o,m,q})}
 for(const list of groups.values())if(list.length>=6)for(const row of list){const baseline=median(list.filter(x=>x!==row).map(x=>x.q));if(baseline>0&&row.q>=4*baseline)signals.push({type:'material_spike',equipment:row.o.equipment,order_id:row.o.id,material:row.m.name,unit:row.m.unit,quantity:row.q,baseline,samples:list.length-1,ratio:row.q/baseline,action:'Сверить списание с фактической работой; история не заменяет норму склада'})}
 const missing=new Map();for(const o of rows){const reason=String(o.rework_reason??'');if(/нет фото|missing.*photo/i.test(reason)){const worker=String(o.assignee_id??o.assignee);if(!missing.has(worker))missing.set(worker,[]);missing.get(worker).push(o)}}
 const counts=[...missing.values()].map(x=>x.length);for(const[key,list]of missing){const others=[...missing.entries()].filter(([other])=>other!==key).map(([,v])=>v.length);const baseline=Math.max(1,...others);if(list.length>=3&&list.length>=2*baseline)signals.push({type:'missing_photo_reworks',worker:list[0].assignee??key,count:list.length,peer_max:baseline,order_ids:list.map(o=>o.id),action:'Проверить полноту фотоотчётов и обучение; не оценка качества ремонта'})}
 return {since,until,orders:rows.length,signals,limits:'Сигналы из загруженного среза; полнота/сопоставимость не гарантированы. Учебный набор, решения за мастером.'};
}
