// Local/staged only. No token, network effects or automatic identity elevation here.
const enc=new TextEncoder();
export function privateStart(update){const m=update?.message;if(!Number.isSafeInteger(update?.update_id)||!m||m.chat?.type!=='private'||!Number.isSafeInteger(m.from?.id)||m.from.is_bot||m.chat.id!==m.from.id)return null;const match=/^\/start(?:@[A-Za-z0-9_]+)? ([A-Za-z0-9_-]{43})$/.exec(m.text||'');return match?{updateId:update.update_id,telegramId:String(m.from.id),chatId:String(m.chat.id),token:match[1]}:null}
export async function hashToken(token){if(!/^[A-Za-z0-9_-]{43}$/.test(token))throw Error('invalid token');return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(token)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export function makeBindingToken(){const b=crypto.getRandomValues(new Uint8Array(32));return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
export function authorizedDelivery(binding,employee,order,notification){return !!(binding&&!binding.revokedAt&&binding.confirmedAt&&order&&employee?.is_active===true&&['worker','master','leader','admin'].includes(employee.role)&&binding.employeeId===employee.id&&notification?.recipient_id===employee.id&&notification?.order_id===order?.id&&!order.cancelled&&((employee.role==='worker'&&order.assignee_id===employee.id)||(employee.role==='master'&&order.master_id===employee.id)||['leader','admin'].includes(employee.role)))}
export function notificationText(n,o,locale='ru'){const head=locale==='kz'?'Tekton · наряд':'Tekton · наряд';return (head+' #'+o.id+'\n'+String(n.message||o.title||'').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'')).slice(0,3500)}
export function miniAppKeyboard(origin){const url=new URL(origin);if(url.protocol!=='https:'||url.username||url.password||url.hash||url.search)throw Error('safe origin required');return {inline_keyboard:[[{text:'Tekton',web_app:{url:url.origin}}]]}}
// An uncertain send is NOT retried: a timeout may have delivered it already.
export async function dispatchOnce({key,claim,load,send,finish,enabled=false}){if(!enabled)return{state:'disabled'};if(!await claim(key))return{state:'duplicate'};try{const c=await load();if(!authorizedDelivery(c.binding,c.employee,c.order,c.notification)){await finish(key,'cancelled');return{state:'cancelled'}};const result=await send(c);if(!result?.ok){await finish(key,'failed');return{state:'failed'}};await finish(key,'sent',result.message_id);return{state:'sent'}}catch{await finish(key,'unknown');return{state:'unknown'}}}
