import {test} from 'node:test';import assert from 'node:assert/strict';
import{privateStart,hashToken,makeBindingToken,authorizedDelivery,dispatchOnce,miniAppKeyboard}from'../supabase/functions/_shared/telegram-core.mjs';
const token='A'.repeat(43);const valid={update_id:1,message:{chat:{id:123,type:'private'},from:{id:123},text:'/start '+token}};
test('private /start only; reject groups, forwarded identity, malformed tokens',()=>{assert.equal(privateStart(valid).telegramId,'123');for(const u of [{...valid,message:{...valid.message,chat:{id:123,type:'group'}}},{...valid,message:{...valid.message,from:{id:999}}},{...valid,message:{...valid.message,text:'/start x'}},{...valid,message:{...valid.message,from:{id:123,is_bot:true}}}])assert.equal(privateStart(u),null)});
test('opaque tokens, only hash stored',async()=>{const a=makeBindingToken(),b=makeBindingToken();assert.match(a,/^[A-Za-z0-9_-]{43}$/);assert.notEqual(a,b);assert.equal((await hashToken(a)).length,64);await assert.rejects(()=>hashToken('bad'))});
const context={binding:{employeeId:'w',confirmedAt:'now',revokedAt:null,chatId:'123'},employee:{id:'w',role:'worker',is_active:true},order:{id:1,assignee_id:'w',master_id:'m',cancelled:false},notification:{id:1,order_id:1,recipient_id:'w',message:'Синтетический наряд (Т)'}};
test('recheck binding, active role and current assignment',()=>{assert.ok(authorizedDelivery(context.binding,context.employee,context.order,context.notification));for(const c of [{...context,binding:{...context.binding,revokedAt:'now'}},{...context,employee:{...context.employee,is_active:false}},{...context,order:{...context.order,assignee_id:'other'}},{...context,order:{...context.order,cancelled:true}},{...context,notification:{...context.notification,recipient_id:'other'}}])assert.ok(!authorizedDelivery(c.binding,c.employee,c.order,c.notification))});
test('disabled by default; dedup; timeout unknown never retry',async()=>{let sends=0;let claimed=false;const states=[];const options={key:'n1',claim:async()=>claimed?false:(claimed=true),load:async()=>context,send:async()=>{sends++;throw Error('uncertain')},finish:async(_,s)=>states.push(s)};assert.equal((await dispatchOnce(options)).state,'disabled');assert.equal(sends,0);assert.equal((await dispatchOnce({...options,enabled:true})).state,'unknown');assert.equal((await dispatchOnce({...options,enabled:true})).state,'duplicate');assert.equal(sends,1);assert.deepEqual(states,['unknown'])});
test('reassignment cancels send and MiniApp URL has no embedded session',async()=>{let sends=0;const r=await dispatchOnce({key:1,enabled:true,claim:async()=>true,load:async()=>({...context,order:{...context.order,assignee_id:'other'}}),send:async()=>{sends++},finish:async()=>{}});assert.equal(r.state,'cancelled');assert.equal(sends,0);assert.deepEqual(miniAppKeyboard('https://naryadai.vercel.app/').inline_keyboard[0][0].web_app,{url:'https://naryadai.vercel.app'});assert.throws(()=>miniAppKeyboard('http://unsafe.test'));assert.throws(()=>miniAppKeyboard('https://site.test/?jwt=secret'))});

test('concurrent duplicate claims send exactly once',async()=>{let claimed=false,sends=0;const options={key:'same-notification',enabled:true,claim:async()=>{if(claimed)return false;claimed=true;return true},load:async()=>context,send:async()=>{sends++;return{ok:true,message_id:1}},finish:async()=>{}};const results=await Promise.all(Array.from({length:20},()=>dispatchOnce(options)));assert.equal(sends,1);assert.equal(results.filter(r=>r.state==='sent').length,1);assert.equal(results.filter(r=>r.state==='duplicate').length,19)});
test('recipient-read failure leaves unknown receipt without a send',async()=>{let sends=0;const states=[];const r=await dispatchOnce({key:1,enabled:true,claim:async()=>true,load:async()=>{throw Error('source unavailable')},send:async()=>{sends++},finish:async(_,state)=>states.push(state)});assert.equal(r.state,'unknown');assert.equal(sends,0);assert.deepEqual(states,['unknown'])});
test('master channel tied to current master; no worker data to unrelated master',()=>{const b={...context.binding,employeeId:'m'},e={id:'m',role:'master',is_active:true},n={...context.notification,recipient_id:'m'};assert.equal(authorizedDelivery(b,e,context.order,n),true);assert.equal(authorizedDelivery(b,e,{...context.order,master_id:'other'},n),false)});
