import {useEffect,useState} from 'react'
import type {Actor} from '../../App'
import * as H from '../../lib/data'
import {catalogFields,catalogPayload,catalogLabels,catalogFieldLabels} from '../../lib/catalog-fields.mjs'
import {Card} from '../../components/ui/card'
import {Button} from '../../components/ui/button'
export default function Catalog({actor}:{actor:Actor}){
 const [state,setState]=useState<any>(null),[entity,setEntity]=useState('sections'),[recordId,setRecordId]=useState(''),[values,setValues]=useState<any>({}),[revision,setRevision]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const reload=async()=>{const data=await H.catalogState();setState(data);return data;};
 useEffect(()=>{if(actor.role==='admin')reload().catch(e=>setError(e.message))},[actor.role]);
 if(actor.role!=='admin')return <p role="alert">Только администратор справочников.</p>;
 const rows=state?.[entity]||[],fields=catalogFields[entity];
 const key=(row:any)=>String(row.id??row.code??row.work_type);
 const reset=()=>{setRecordId('');setRevision(null);setValues({criticality:'normal',on_shift:true,is_active:true});setNotice('')};
 const edit=async(id:string)=>{setBusy(true);setError('');try{const r=await H.catalogRecord(entity,id);setRecordId(id);setValues(r.record);setRevision(r.revision);setNotice('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const save=async(action:'create'|'update'|'delete')=>{setBusy(true);setError('');try{const r=await H.catalogWrite(entity,action,recordId,catalogPayload(entity,values),revision);await reload();setNotice(action==='delete'?'Удалено. Изменение записано в журнале.':'Сохранено. Изменение записано в журнале.');if(r.record){setRecordId(r.id);setValues(r.record);setRevision(r.revision)}else reset()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <div className="space-y-4"><h1 className="text-2xl font-bold">Справочники</h1><p>Учебные данные. RPC доступен только admin; каждое изменение с автором и версией. Создание/удаление учётных записей и назначение ролей здесь недоступны.</p><label>Справочник<select aria-label="Справочник" className="w-full border p-3" value={entity} onChange={e=>{setEntity(e.target.value);reset()}}>{Object.keys(catalogFields).map(k=><option key={k} value={k}>{catalogLabels[k]}</option>)}</select></label>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <Card><h2>Записи: {rows.length}</h2><div className="space-y-2">{rows.map((row:any)=><button className="block border rounded p-3 min-h-14 w-full text-left" disabled={busy} key={key(row)} onClick={()=>edit(key(row))}>{row.name??row.work_type} · {key(row)}</button>)}</div>{entity!=='employees'&&<Button disabled={busy} onClick={reset}>Новая запись</Button>}</Card>
 <Card><h2>{recordId?'Изменение записи '+recordId:'Новая запись'}</h2>{fields.map(field=><label className="block mt-3" key={field}>{catalogFieldLabels[field]||field}{['on_shift','is_active'].includes(field)?<select aria-label={field} className="w-full border p-3" value={String(values[field]??true)} onChange={e=>setValues((v:any)=>({...v,[field]:e.target.value==='true'}))}><option value="true">Да</option><option value="false">Нет</option></select>:field==='criticality'?<select aria-label={field} className="w-full border p-3" value={values[field]||'normal'} onChange={e=>setValues((v:any)=>({...v,[field]:e.target.value}))}>{[['low','Низкая'],['normal','Обычная'],['high','Высокая']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select>:['section_id','brigade'].includes(field)?<select aria-label={field} className="w-full border p-3" value={values[field]??''} onChange={e=>setValues((v:any)=>({...v,[field]:e.target.value}))}><option value="">Выбрать</option>{(field==='section_id'?state?.sections||[]:state?.crews||[]).map((r:any)=><option key={r.id} value={field==='section_id'?r.id:r.name}>{r.name}</option>)}</select>:<input aria-label={field} className="w-full border p-3" type={['section_id','norm_minutes'].includes(field)?'number':'text'} maxLength={1000} value={values[field]??''} disabled={!!recordId&&['code','work_type'].includes(field)} onChange={e=>setValues((v:any)=>({...v,[field]:e.target.value}))}/>}</label>)}<Button disabled={busy||entity==='employees'&&!recordId} onClick={()=>save(recordId?'update':'create')}>Сохранить справочник</Button>{recordId&&entity!=='employees'&&<Button disabled={busy} variant="outline" onClick={()=>{if(window.confirm('Удалить запись? Связанные записи удалять нельзя.'))save('delete')}}>Удалить запись</Button>}</Card></div>
}
