import http from 'node:http';import pg from 'pg';import{readFileSync}from'node:fs';import{randomBytes,createHash}from'node:crypto';import{checkClosure,transitions}from'./domain.mjs';
const cfg={host:'127.0.0.1',port:5433,user:'postgres',password:readFileSync('.local/db-secret','utf8'),database:'naryadai'};
const pool=new pg.Pool({...cfg,max:8});pool.on('error',e=>console.error('Database pool connection error',e.message));const sessions=new Map();const listeners=new Set();
async function inActor(actor,fn){const c=await pool.connect();try{await c.query('begin');await c.query('set local role naryad_app');await c.query("select set_config('app.actor_id',$1,true)",[actor.id]);const result=await fn(c);await c.query('commit');return result}catch(e){await c.query('rollback');throw e}finally{c.release()}}
const watcher=new pg.Client(cfg);await watcher.connect();await watcher.query('listen orders_changed');watcher.on('notification',()=>{for(const r of listeners)r.write('data: changed\n\n')});watcher.on('error',e=>console.error('Realtime connection failed',e));
function send(res,status,body){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(body))}
async function body(req){let s='';for await(const b of req){s+=b;if(s.length>2500000)throw new Error('payload too large')}return s?JSON.parse(s):{}}
function auth(req){const token=req.headers.cookie?.match(/naryad_session=([^;]+)/)?.[1];return sessions.get(token)}
let deadlineBusy=false;const timer=setInterval(async()=>{if(deadlineBusy)return;deadlineBusy=true;try{await pool.query('select check_deadlines()')}catch(e){console.error('Deadline worker failed',e.message)}finally{deadlineBusy=false}},30000);
const server=http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,'http://localhost');
 if(req.method==='POST'&&url.pathname==='/api/demo-login'){const x=await body(req);const employee=(await pool.query('select id,name,role from employees where id=$1',[x.employee_id])).rows[0];if(!employee)return send(res,400,{error:'Unknown demo account'});const token=randomBytes(32).toString('hex');sessions.set(token,{...employee,expires:Date.now()+8*3600000});res.setHeader('Set-Cookie',`naryad_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`);return send(res,200,{employee,mode:'local_demo'});}
 if(req.method==='GET'&&url.pathname==='/api/demo-accounts')return send(res,200,{employees:(await pool.query('select id,name,role from employees order by role')).rows});
 const actor=auth(req);if(!actor||actor.expires<Date.now())return send(res,401,{error:'Войдите в тестовую учётку'});
 if(req.method==='GET'&&url.pathname==='/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write('data: connected\n\n');listeners.add(res);const heartbeat=setInterval(()=>res.write(': heartbeat\n\n'),20000);req.on('close',()=>{listeners.delete(res);clearInterval(heartbeat)});return;}
 if(req.method==='GET'&&url.pathname==='/api/state'){const x=await inActor(actor,async c=>({orders:(await c.query('select o.*,e.name equipment,s.name section,p.name assignee from orders o join equipment e on e.id=o.equipment_id join sections s on s.id=e.section_id join employees p on p.id=o.assignee_id order by o.id desc')).rows,employees:(await c.query('select id,name,role,specialty,on_shift from employees order by name')).rows,equipment:(await c.query('select e.*,s.name section from equipment e join sections s on s.id=e.section_id')).rows,fault_codes:(await c.query('select * from fault_codes')).rows,materials:(await c.query('select * from materials')).rows,notifications:(await c.query('select * from notifications order by created_at desc limit 30')).rows,events:(await c.query('select ev.*,p.name actor from order_events ev join employees p on p.id=ev.actor_id order by ev.id desc limit 200')).rows}));return send(res,200,{...x,actor,backend:'Локальный PostgreSQL · RLS · LISTEN/NOTIFY',ai_mode:'rules'});}
 if(req.method==='GET'&&url.pathname==='/api/equipment-history'){const equipmentId=Number(url.searchParams.get('id'));if(!Number.isInteger(equipmentId)||equipmentId<1)throw Error('Equipment id required');const data=await inActor(actor,async c=>({orders:(await c.query('select * from order_report where equipment_id=$1 order by created_at desc limit 200',[equipmentId])).rows,events:(await c.query('select ev.*,o.title from order_events ev join orders o on o.id=ev.order_id where o.equipment_id=$1 order by ev.created_at desc limit 200',[equipmentId])).rows}));return send(res,200,data);}
if(req.method==='GET'&&url.pathname==='/api/report'){const report=await inActor(actor,async c=>{const since=url.searchParams.get('since'),until=url.searchParams.get('until');if(since&&Number.isNaN(Date.parse(since))||until&&Number.isNaN(Date.parse(until)))throw Error('Invalid report dates');const rows=(await c.query('select * from order_report where ($1::timestamptz is null or created_at>=$1) and ($2::timestamptz is null or created_at<=$2) order by created_at desc limit 1000',[since,until])).rows;const employees=(await c.query("select id,name from employees where role='worker'")).rows;const fullRatings=(await c.query('select * from employee_ratings')).rows;const ratings=employees.map(e=>{const done=rows.filter(o=>o.assignee_id===e.id&&o.status==='closed');const timely=done.filter(o=>o.on_time).length;const rework=done.filter(o=>o.had_rework).length;const full=fullRatings.find(r=>r.id===e.id);return {...e,...full,closed:done.length,on_time:timely,rework,score:done.length?Math.round(70*timely/done.length+30*(1-rework/done.length)):null,formula:'70% срок + 30% без доработки. Качество не оценено; объём и отказы пока не учтены.'}});const equipment=Object.values(rows.reduce((a,o)=>{const k=o.equipment;a[k]??={name:k,orders:0,downtime_minutes:0};a[k].orders++;a[k].downtime_minutes+=Number(o.duration_minutes||0);return a},{}));return {rows,ratings,equipment,generated_at:new Date().toISOString(),source:'synthetic',full_rating_formula:'40% качество мастера, 25% срок, 20% без доработки/повтора 7 дней, 10% сложность/объём, 5% отказы. Полный балл не выдаётся без оценки качества.',limits:['История синтетическая','Показатель не является подтверждённым эффектом предприятия','Качество ремонта без модели и оценки мастера не измерено']}});return send(res,200,report);}
if(req.method==='POST'&&url.pathname==='/api/orders'){const x=await body(req);if(!x.title?.trim()||x.title.length>1000)throw new Error('Описание обязательно');const data=await inActor(actor,async c=>(await c.query('insert into orders(title,kind,equipment_id,assignee_id,master_id,priority,deadline) values($1,$2,$3,$4,$5,$6,$7) returning id',[x.title,x.kind,x.equipment_id,x.assignee_id,actor.id,x.priority,x.deadline])).rows[0]);return send(res,201,data);}
 const m=url.pathname.match(/^\/api\/orders\/(\d+)\/transition$/);
 if(req.method==='POST'&&m){const x=await body(req);const data=await inActor(actor,async c=>{const o=(await c.query('select * from orders where id=$1 for update',[m[1]])).rows[0];if(!o)throw new Error('Наряд недоступен');if(o.version!==x.version)throw new Error('Данные изменились. Обновите наряд');if(!transitions[o.status]?.includes(x.status))throw new Error('Недопустимый переход');await c.query("select set_config('app.reason',$1,true)",[x.reason||'']);let closure=x.status==='completed'?x.closure:o.closure;if(x.status==='completed'&&checkClosure({...closure,kind:o.kind}).verdict==='rework')throw new Error(checkClosure({...closure,kind:o.kind}).reasons.join('; '));if(x.status==='completed'){const evidence=[];for(const photo of closure.photos||[]){const match=photo.match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/);if(!match)throw Error('Неверный формат фото');const bytes=Buffer.from(match[2],'base64');const png=bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const webp=bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP';if(!(png||jpg||webp)||bytes.length>300000)throw Error('Недопустимое или слишком большое фото');const hash=createHash('sha256').update(bytes).digest('hex');const duplicate=(await c.query('select order_id from order_photos where sha256=$1 and order_id<>$2 limit 1',[hash,o.id])).rows[0];await c.query('insert into order_photos(order_id,uploaded_by,sha256,byte_size,mime_type) values($1,$2,$3,$4,$5)',[o.id,actor.id,hash,bytes.length,match[1]]);evidence.push({sha256:hash,server_received_at:new Date().toISOString(),byte_size:bytes.length,duplicate_order_id:duplicate?.order_id||null,limits:'Время получения сервером, не доказательство времени съёмки'});}closure={...closure,photo_evidence:evidence};}let ai=x.status==='ai_review'?checkClosure({...closure,kind:o.kind}):o.ai_result;if(x.status==='ai_review'&&closure?.photo_evidence?.some(p=>p.duplicate_order_id))ai={...ai,reasons:[...ai.reasons,'Фото совпадает с ранее загруженным. Мастер должен проверить источник.']};if(x.status==='closed'){if(!Number.isInteger(x.human_score)||x.human_score<1||x.human_score>5)throw new Error('Оценка мастера от 1 до 5 обязательна');ai={...ai,human_score:x.human_score,human_comment:x.human_comment||''};}return(await c.query('update orders set status=$1,closure=$2,ai_result=$3 where id=$4 returning id,status,version',[x.status,closure,ai,m[1]])).rows[0]});return send(res,200,data);}
 send(res,404,{error:'Not found'});
}catch(e){console.error('Request failed',req.method,req.url,e.message);send(res,400,{error:e.message})}});
server.listen(3001,'127.0.0.1',()=>console.log('Private local API ready on 127.0.0.1:3001'));
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,async()=>{clearInterval(timer);server.close();for(const r of listeners)r.end();await watcher.end();await pool.end();process.exit(0)});
