import {useState} from 'react'
import {Link} from 'react-router-dom'
import {checkPriority,DEFAULT_CHECK_CONFIG} from '../lib/check-priority.mjs'
import {useLocale} from '../lib/locale'
const copy = {
 ru:{title:'Приоритет проверки',source:'Правила · учебный набор · не вероятность отказа',review:'Проверить причины повторов',below:'Порог не достигнут. Это не подтверждение исправности.',insufficient:'Недостаточно сопоставимых закрытых нарядов',window:'Окно повтора, дней',threshold:'Порог, пар',settings:'Настроить правила',pair:'Пар повторов',eligible:'Сопоставимых нарядов',missing:'Исключено из-за неполных или неоднозначных данных',details:'Почему такой приоритет',code:'Шифр',gap:'Между датами создания',closed:'Закрытия нарядов',overlap:'Новый наряд открыт до закрытия предыдущего. Это не повтор после завершённого ремонта.',days:'дн.',scope:'Последние 90 дней в загруженной истории и пределах прав роли. История может быть неполной. Только закрытые внеплановые наряды; соседние по шифру. Причину и действие выбирает мастер.',asof:'Расчёт на',empty:'Подходящих пар нет',draft:''},
 kz:{title:'Тексеру басымдығы',source:'Ережелер · оқу деректері · істен шығу ықтималдығы емес',review:'Қайталану себептерін тексеру',below:'Шекке жеткен жоқ. Бұл жарамдылықты растамайды.',insufficient:'Салыстыруға болатын жабылған нарядтар жеткіліксіз',window:'Қайталану аралығы, күн',threshold:'Шек, жұп',settings:'Ережелерді баптау',pair:'Қайталану жұптары',eligible:'Салыстырылатын нарядтар',missing:'Толық емес немесе екіұшты деректерге байланысты есепке алынбады',details:'Бұл басымдықтың себебі',code:'Код',gap:'Жасалған күндер арасындағы уақыт',closed:'Нарядтардың жабылуы',overlap:'Жаңа наряд алдыңғысы жабылғанға дейін ашылған. Бұл аяқталған жөндеуден кейінгі қайталану емес.',days:'күн',scope:'Жүктелген тарихтағы соңғы 90 күн, рөлге берілген құқықтар шегінде. Тарих толық болмауы мүмкін. Тек жабылған жоспардан тыс нарядтар; бір код бойынша көршілес. Себеп пен әрекетті шебер анықтайды.',asof:'Есептеу уақыты',empty:'Сәйкес жұптар жоқ',draft:'Қазақша мәтін: жоба, маманның тексеруі қажет.'}
}
export default function CheckPriorityPanel({orders,equipment,canOpenOrders=true,asOf}:{orders:any[];equipment:{id:string|number;name:string}[];canOpenOrders?:boolean;asOf?:number}) {
 const {locale}=useLocale();const c=copy[locale as 'ru'|'kz'];const [at]=useState(()=>asOf??Date.now())
 const [windowDays,setWindowDays]=useState(DEFAULT_CHECK_CONFIG.repeatWindowDays);const [threshold,setThreshold]=useState(DEFAULT_CHECK_CONFIG.pairThreshold)
 const results=equipment.map(eq=>({eq,result:checkPriority(orders,eq.id,{repeatWindowDays:windowDays,pairThreshold:threshold},at)})).sort((a,b)=>b.result.pairCount-a.result.pairCount||String(a.eq.id).localeCompare(String(b.eq.id)))
 const format=(date:string)=>new Date(date).toLocaleString(locale==='kz'?'kk-KZ':'ru-RU',{timeZone:'Asia/Almaty',day:'numeric',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})
 const order=(id:string|number)=>canOpenOrders?<Link className="underline break-all" to={'/orders/'+encodeURIComponent(String(id))}>#{id}</Link>:<span className="break-all">#{id}</span>
 return <section data-testid="check-priority" className="border border-border rounded-2xl p-4 space-y-3 min-w-0" aria-label={c.title}>
 <h2 className="text-lg font-bold">{c.title}</h2><p className="text-xs text-muted">{c.source}</p>
 <details><summary className="min-h-11 py-3 cursor-pointer">{c.settings}</summary><div className="flex flex-wrap gap-4"><label className="text-sm">{c.window}<select aria-label={c.window} className="block border rounded-lg min-h-11 px-3 mt-1" value={windowDays} onChange={e=>setWindowDays(Number(e.target.value))}>{[3,7,14,30].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label className="text-sm">{c.threshold}<select aria-label={c.threshold} className="block border rounded-lg min-h-11 px-3 mt-1" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}>{[1,2,3,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div></details>
 <p className="text-xs text-muted">{c.asof}: {format(new Date(at).toISOString())}</p>
 {!results.length&&<p>{c.insufficient}</p>}
 {results.slice(0,5).map(({eq,result:r})=><article key={eq.id} className="border-t border-border pt-3 space-y-2 min-w-0"><h3 className="font-semibold break-words"><Link className="underline" to={'/equipment/'+encodeURIComponent(String(eq.id))}>{eq.name}</Link></h3><p className={r.status==='review'?'font-semibold text-amber-700':'text-sm'}>{c[r.status==='review'?'review':r.status==='insufficient'?'insufficient':'below']}</p><p className="text-sm">{c.pair}: {r.pairCount} · {c.eligible}: {r.eligibleCount}</p>{r.missingCount>0&&<p className="text-xs text-muted">{c.missing}: {r.missingCount}</p>}<details><summary className="min-h-11 py-3 cursor-pointer">{c.details}</summary>{!r.pairs.length?<p className="text-sm">{c.empty}</p>:<ol className="space-y-3 text-sm">{r.pairs.map((p,i)=><li className="border rounded-xl p-3 break-words" key={i}><p>{c.code}: {p.code} · {order(p.firstOrderId)} → {order(p.secondOrderId)}</p><p>{c.gap}: {Number(p.gapDays.toFixed(2))} {c.days}</p><p className="text-xs text-muted">{format(p.firstCreatedAt)} → {format(p.secondCreatedAt)}</p><p className="text-xs text-muted">{c.closed}: {format(p.firstClosedAt)} → {format(p.secondClosedAt)}</p>{p.overlappingWork&&<p className="text-xs font-semibold">{c.overlap}</p>}</li>)}</ol>}</details></article>)}
 <p className="text-xs text-muted">{c.scope}</p>{c.draft&&<p className="text-xs text-muted">{c.draft}</p>}
 </section>
}
