import {createPortal} from 'react-dom'
import {useEffect,useRef,useState} from 'react'
const steps=[
 ['Панель смены','Мастер видит загрузку, свободного слесаря и очередь. Этот тур не читает и не меняет рабочие наряды.'],
 ['Авария','Насос (Т): синтетическая течь. Выбор исполнителя по специальности, статусу и допуску; назначение подтверждает мастер.'],
 ['Приём и начало','Исполнитель принимает и начинает. Настоящие push и обновление ≤5 секунд проверяются отдельно на телефонах.'],
 ['Очередь и срок','Второй наряд (Т) ждёт. Ускорение здесь меняет только демонстрационные часы.'],
 ['Сдача и проверка','Текст работ, шифр, материалы и фото после. Проверка обязательных полей не доказывает физическое качество.'],
 ['Доработка','Синтетический негативный пример: нет фото и списано 80 единиц. Результат заранее задан для тура, это не свежий ответ модели.'],
 ['Решение мастера','Мастер проверяет результат и закрывает или возвращает в работу. ИИ не закрывает автоматически.'],
 ['Отчёт и история','Рейтинг и синтетические паттерны. Проверки расчёта показаны отдельно.']
]
export default function DemoTour(){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0),[minutes,setMinutes]=useState(0),[emergency,setEmergency]=useState(false),[reject,setReject]=useState(false);const close=useRef<HTMLButtonElement>(null),launch=useRef<HTMLButtonElement>(null)
 useEffect(()=>{if(!open)return;const prior=document.body.style.overflow;document.body.style.overflow='hidden';close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){const nodes=[...document.querySelectorAll<HTMLButtonElement>('.tekton-demo-dialog button')].filter(x=>!x.disabled);const a=nodes[0],z=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===a){e.preventDefault();z?.focus()}else if(!e.shiftKey&&document.activeElement===z){e.preventDefault();a?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=prior;document.removeEventListener('keydown',key);launch.current?.focus()}},[open])
 return <><button ref={launch} type="button" className="tekton-demo-launch" onClick={()=>{setOpen(true);setStep(0);setMinutes(0);setEmergency(false);setReject(false)}}>ДЕМО / ИННОВАЦИИ</button>{open&&createPortal(<div className="tekton-demo-backdrop" onClick={()=>setOpen(false)}><section className="tekton-demo-dialog" role="dialog" aria-modal="true" aria-labelledby="tekton-demo-title" onClick={e=>e.stopPropagation()}><div className="tekton-demo-top"><span>СИНТЕТИЧЕСКИЕ ДАННЫЕ · БЕЗ ОТПРАВКИ</span><button ref={close} onClick={()=>setOpen(false)}>Закрыть</button></div><h2 id="tekton-demo-title">Тур: 1–2 минуты</h2><p className="tekton-demo-muted">Изолированный тур. Без БД, уведомлений и вызова модели.</p><div className="tekton-demo-stage" aria-live="polite"><small>Шаг {step+1} из {steps.length}</small><h3>{steps[step][0]}</h3><p>{steps[step][1]}</p></div><div className="tekton-demo-nav"><button disabled={step===0} onClick={()=>setStep(x=>x-1)}>Назад</button><button disabled={step===steps.length-1} onClick={()=>setStep(x=>x+1)}>Далее</button></div><h3>Триггеры для показа</h3><div className="tekton-demo-triggers"><button onClick={()=>setEmergency(true)}>Создать аварию (Т)</button><button onClick={()=>setReject(true)}>Показать доработку ИИ (Т)</button><button onClick={()=>setMinutes(x=>x+15)}>Ускорить +15 мин (Т)</button></div><div className="tekton-demo-result" aria-live="polite"><p>Часы демо: +{minutes} мин. Реальные сроки не изменены.</p>{emergency&&<p>Наряд ДЕМО-1 (Т): течь насоса · аварийный · выдан только внутри тура. Уведомление не отправлено.</p>}{minutes>=15&&<p>ДЕМО-2 (Т): просрочен на {minutes-10} мин · в очереди. Это локальная иллюстрация, не серверное уведомление.</p>}{reject&&<p>ДЕМО-3 (Т): требует доработки. Нет фото после, количество материала 80. Заранее заданный результат; модель не вызывалась.</p>}</div></section></div>,document.body)}</>
}
