import {useLocale} from '../lib/locale'
import {equipmentRiskSignal} from '../lib/equipment-risk-signal.mjs'
import {orderForecast} from '../lib/order-forecast.mjs'
import {Link} from 'react-router-dom'
export default function OrderForecastPanel({orders,equipment,section='',offline=false}:{orders:any[],equipment:any[],section?:string,offline?:boolean}){
 const {t,locale}=useLocale();const asOf=Date.now();const rows=equipment.filter(e=>!section||e.section===section).map(e=>({equipment:e,forecast:orderForecast(orders,e.id,{asOf})}));
 const date=(at:number)=>new Date(at).toLocaleDateString(locale==='kz'?'kk-KZ':'ru-RU',{timeZone:'Asia/Almaty',day:'numeric',month:'short'});
 return <section className="tk-card order-forecast-panel"><h2>{t('Прогноз следующего наряда')}</h2><p>{t('По истории внеплановых назначений. Не прогноз отказа оборудования.')}</p>{offline&&<p role="status">{t('Офлайн: прогноз по сохранённому срезу, данные могут быть устаревшими.')}</p>}{rows.map(({equipment:e,forecast:f})=><div className="forecast-row" key={e.id}><strong>{e.name}</strong>{f.state==='thin'||f.state==='unavailable'?<b>{t('Мало данных')}</b>:<><b>{f.state==='elapsed'?t('Окно прошло: проверьте историю'):date(f.expectedAt)}</b><span>{t('Исторический диапазон:')} {date(f.rangeStart)} - {date(f.rangeEnd)}</span><span>{t('Медиана интервала:')} {f.medianDays.toFixed(1)} {t('дней')}</span></>}<div className="text-xs mt-2">{(()=>{const r=equipmentRiskSignal(orders,e.id,asOf);return r.status==='insufficient_data'?<span>Сигнал нагрузки: мало данных (n={r.n})</span>:<><b>Сигнал внеплановых нарядов</b><p>{r.n_recent} за 30 дней · ранее {r.n_prior} за 60 дней</p><p>Ставка на 30 дней: {r.expectedOrders30d.toFixed(1)} · диапазон 80%: {r.range80Orders30d[0].toFixed(1)}-{r.range80Orders30d[1].toFixed(1)}</p><p>{r.limitations}</p></>})()}</div><small>{f.count} {t('нарядов ·')} {f.intervalCount||0} {t('интервалов за 180 дней')}</small>{f.lastAt&&<small>{t('Последний наряд:')} {date(f.lastAt)}</small>}<Link to={'/equipment/'+e.id}>{t('История')}</Link></div>)}{rows.length===0&&<p>{t('Доступного оборудования нет.')}</p>}<details><summary>{t('Как считается прогноз')}</summary><p>{t('Медиана положительных интервалов между датами создания внеплановых нарядов. Минимум 6 нарядов и 5 интервалов. Диапазон: 10-й и 90-й процентили истории, не доверительный интервал. Повторные ID, отменённые, отклонённые и будущие записи исключены. Если окно прошло, прогноз не переносится на завтра.')}</p><p>{t('Точность не измерена. Неполная история, задержка регистрации и изменение нагрузки меняют оценку. Используется доступный срез, до 600 записей. План работ не меняется автоматически.')}</p></details></section>
}
