import {edgeOverlay} from '../lib/photo-outline.mjs'
import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
export default function PhotoCapture({reference,onCapture,onClose}:{reference?:string,onCapture:(f:File)=>Promise<void>,onClose:()=>void}){
 const initialFocus=useRef(document.activeElement as HTMLElement|null)
 const dialog=useRef<HTMLDivElement>(null),picker=useRef<HTMLInputElement>(null)
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null)
 const [outline,setOutline]=useState(''),[mode,setMode]=useState<'outline'|'photo'|'hide'>('outline')
 useEffect(()=>{if(!reference)return;let active=true;const image=new Image();image.crossOrigin='anonymous';image.onload=()=>{try{const c=document.createElement('canvas');c.width=480;c.height=Math.max(1,Math.round(image.height/image.width*480));const ctx=c.getContext('2d')!;ctx.drawImage(image,0,0,c.width,c.height);const pixels=ctx.getImageData(0,0,c.width,c.height);pixels.data.set(edgeOverlay(pixels.data,c.width,c.height));ctx.putImageData(pixels,0,0);if(active)setOutline(c.toDataURL())}catch{/* signed image/CORS blocked: use original ghost */}};image.src=reference;return()=>{active=false}},[reference])
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[opacity,setOpacity]=useState(.3)
 useEffect(()=>{const trigger=initialFocus.current;const background=document.getElementById('root');const priorInert=background?.inert;if(background)background.inert=true;let alive=true;const previous=document.body.style.overflow;document.body.style.overflow='hidden';if(!navigator.mediaDevices?.getUserMedia){setError('Камера недоступна. Выберите фото.')}else navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false}).then(s=>{if(!alive){s.getTracks().forEach(t=>t.stop());return}stream.current=s;if(video.current){video.current.srcObject=s;video.current.play().catch(()=>setError('Камера не запустилась. Выберите фото.'))}}).catch(()=>setError('Камера недоступна. Разрешите доступ или выберите фото.'));const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=[...dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled):not([type=file])')||[]];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{alive=false;stream.current?.getTracks().forEach(t=>t.stop());document.body.style.overflow=previous;document.removeEventListener('keydown',key);if(background)background.inert=priorInert||false;trigger?.focus()}},[])
 const save=async(f:File)=>{setBusy(true);setError('');try{await onCapture(f);onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const capture=()=>{const v=video.current;if(!v?.videoWidth)return;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d')!.drawImage(v,0,0);c.toBlob(b=>{if(b)save(new File([b],'repair-after.jpg',{type:'image/jpeg'}));else setError('Снимок не получен')},'image/jpeg',.85)}
 return createPortal(<div ref={dialog} className="photo-capture-dialog fixed inset-0 z-[100] bg-[#12161E] text-white overflow-y-auto" role="dialog" aria-modal="true" aria-label="Снимок после ремонта"><div className="p-4 flex justify-between items-center"><h2 className="text-lg font-semibold">Повтори ракурс</h2><button autoFocus className="min-h-12 px-4 border rounded-xl" onClick={onClose}>Закрыть</button></div><div className="relative mx-4 aspect-[3/4] overflow-hidden rounded-2xl bg-black"><video ref={video} muted playsInline onLoadedData={()=>setReady(true)} className="absolute inset-0 w-full h-full object-contain"/>{reference&&mode!=='hide'&&<img src={mode==='outline'&&outline?outline:reference} style={{opacity:mode==='outline'?Math.min(1,opacity*2):opacity}} className="absolute inset-0 w-full h-full object-contain pointer-events-none" alt="Ориентир ракурса по фото до"/>}<div className="absolute inset-6 border border-white/40 rounded-xl pointer-events-none"/></div><div className="p-4 space-y-3"><p className="text-sm">{reference?'Совмести оборудование с ориентиром. Не приближайся к работающему оборудованию.':'Фото до отсутствует. Снимите узел с безопасной позиции.'}</p>{reference&&<div className="flex gap-2">{([['outline','Контур'],['photo','Фото до'],['hide','Скрыть']] as const).map(([m,label])=><button className="min-h-12 flex-1 border rounded-xl" style={{background:mode===m?'#d5ab5b':'transparent',color:mode===m?'#12161e':'white'}} onClick={()=>setMode(m)} key={m}>{label}</button>)}</div>}{reference&&<label className="block text-sm">Прозрачность ориентира<input aria-label="Прозрачность ориентира" className="block w-full min-h-12" type="range" min="0" max=".7" step=".05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label>}{error&&<p role="alert" className="text-amber-300">{error}</p>}<button className="w-full min-h-16 bg-white text-black rounded-xl font-bold disabled:opacity-40" disabled={!ready||busy} onClick={capture}>{busy?'Сохранение…':'Снять фото после'}</button><button type="button" className="flex w-full justify-center items-center min-h-12 border rounded-xl" disabled={busy} onClick={()=>picker.current?.click()}>Выбрать фото</button><input ref={picker} className="hidden" type="file" accept="image/*" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)save(f)}}/></div></div>,document.body)
}
