import {useState} from 'react'
import {supabase} from '../lib/data'
import {useLocale} from '../lib/locale'
import {makeBindingToken,hashToken} from '../../supabase/functions/_shared/telegram-core.mjs'
export default function TelegramPairing(){const {t}=useLocale();const [link,setLink]=useState(''),[pending,setPending]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false)
 const configured=import.meta.env.VITE_TELEGRAM_PAIRING==='true'
 async function rpc(name:string,args:any={}){if(!supabase)throw Error('Авторизация недоступна');const {data,error}=await supabase.rpc(name,args);if(error)throw Error('Привязка пока недоступна');return data}
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="tk-card p-3.5 space-y-3" aria-label="Telegram"><h3>Telegram</h3>{!configured?<p>{t('Telegram: подключение пока не включено.')}</p>:<><p>{t('Откройте бота, затем вернитесь сюда и подтвердите аккаунт.')}</p><button className="min-h-14 border rounded-lg px-3 w-full" disabled={busy} onClick={()=>action(async()=>{const token=makeBindingToken();await rpc('telegram_pair_create',{p_hash:await hashToken(token)});setLink('https://t.me/TektonOSdreamlabs_bot?start='+token);setPending(null);setDone(false)})}>{t('Получить ссылку на 10 минут')}</button>{link&&<a className="block min-h-14 border rounded-lg p-3" href={link} target="_blank" rel="noreferrer">{t('Открыть бота')}</a>}<button className="min-h-14 border rounded-lg px-3 w-full" disabled={busy} onClick={()=>action(async()=>setPending(await rpc('telegram_pair_status')))}>{t('Проверить подключение')}</button>{pending?.pending_chat&&!pending.confirmed&&<div><p>Telegram ID: {pending.pending_chat}</p><p>{t('Это ваш аккаунт? Подтвердите только свой ID.')}</p><button className="min-h-14 border rounded-lg px-3 w-full" disabled={busy} onClick={()=>action(async()=>{const ok=await rpc('telegram_pair_confirm',{p_id:pending.id,p_expected_chat:pending.pending_chat});if(!ok)throw Error('Подтверждение недоступно');setDone(true);setLink('');setPending(null)})}>{t('Подтвердить мой аккаунт')}</button></div>}{done&&<p>{t('Аккаунт подтверждён. Доставка ещё требует теста.')}</p>}<button className="min-h-14 border rounded-lg px-3 w-full" disabled={busy} onClick={()=>action(async()=>{await rpc('telegram_disconnect');setLink('');setPending(null);setDone(false)})}>{t('Отключить Telegram')}</button></>}{error&&<p role="alert">{error}</p>}</section>
}
