import EmbeddedPostgres from 'embedded-postgres';
import {existsSync,mkdirSync,readFileSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
import {writeFileSync} from 'node:fs';
mkdirSync('.local',{recursive:true});
if(!existsSync('.local/db-secret'))writeFileSync('.local/db-secret',randomBytes(24).toString('hex'),{mode:0o600});
const password=readFileSync('.local/db-secret','utf8');
const db=new EmbeddedPostgres({databaseDir:'.local/postgres',user:'postgres',password,port:5433,persistent:true,postgresFlags:['-c','listen_addresses=127.0.0.1']});
if(!existsSync('.local/postgres/PG_VERSION'))await db.initialise();
await db.start();
const client=db.getPgClient();await client.connect();
if(!(await client.query("select 1 from pg_database where datname='naryadai'")).rowCount)await db.createDatabase('naryadai');
await client.end();console.log('Local PostgreSQL ready on 127.0.0.1:5433');
process.on('SIGTERM',async()=>{await db.stop();process.exit(0)});
process.on('SIGINT',async()=>{await db.stop();process.exit(0)});
setInterval(()=>{},60000);
