import {chromium} from 'playwright'
const b=await chromium.launch()
const mob=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true})
const w=await mob.newPage()
w.on('response',async r=>{if(r.url().includes('rpc')||r.url().includes('rest'))console.log('NET',r.status(),r.url().slice(-80), (await r.text()).slice(0,200))})
w.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text().slice(0,200))})
await w.goto('http://localhost:4173/login');await w.fill('input[type=email]','worker-c@naryadai.test');await w.fill('input[type=password]',process.env.PW_WORKERC);await w.click('button:has-text("Войти")')
await w.waitForSelector('text=E2E-TEST phone-cycle',{timeout:30000})
await w.goto('http://localhost:4173/orders/'+process.env.OID)
await w.waitForSelector('button:has-text("Допуск подтверждён")',{timeout:15000})
await w.click('button:has-text("Допуск подтверждён")');await w.waitForTimeout(500)
await w.fill('input[placeholder*="Номер допуска"]','Наряд-допуск №E2E, мастер Петров')
await w.waitForTimeout(300)
const dis=await w.locator('button:has-text("Отметить допуск")').isDisabled()
console.log('permit submit disabled?',dis)
await w.click('button:has-text("Отметить допуск")',{force:true})
await w.waitForTimeout(2500)
console.log('ERR BANNER:', await w.locator('.text-tk-red').allInnerTexts().catch(()=>[]))
console.log('permit line:', await w.locator('text=Допуск подтверждён').count())
await w.screenshot({path:'/tmp/dbg-permit.png'})
await b.close()
