import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-b@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERB)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/orders/646'); await pg.waitForTimeout(2500)
console.log('checkboxes:',await pg.locator('input[type=checkbox]').count())
console.log('gatebtn:',await pg.locator('button:has-text("Подтвердить и начать работу")').count())
console.log('disabled:',await pg.locator('button:has-text("Подтвердить и начать работу")').isDisabled().catch(e=>'n/a'))
console.log('body has gate:',(await pg.content()).includes('Перед началом работ'))
console.log('orderfound:',(await pg.content()).includes('646'))
await pg.screenshot({path:'/tmp/dbg-646.png'})
await b.close()
