import {chromium} from '@playwright/test'
const b=await chromium.launch()
const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'allow',permissions:['notifications']})
const pg=await ctx.newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
console.log('inputs:', await pg.locator('input').evaluateAll(els=>els.map(e=>e.type+'/'+e.name+'/'+e.placeholder)))
await pg.locator('input').first().fill('worker-c@naryadai.test')
await pg.locator('input').nth(1).fill(process.env.PW_WORKERC)
console.log('filled:', await pg.locator('input').first().inputValue())
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
console.log('url:', pg.url())
console.log('body:', (await pg.locator('body').innerText()).slice(0,200).replace(/\n/g,' | '))
await b.close()
