import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-a@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERA)
await pg.click('button:has-text("Войти")')
await pg.waitForTimeout(6000)
const info=await pg.evaluate(()=>{const n=document.querySelector('nav');const r=n.getBoundingClientRect();const cs=getComputedStyle(n);return{top:r.top,bottom:r.bottom,height:r.height,position:cs.position,display:cs.display,bg:cs.backgroundColor,z:cs.zIndex,vh:innerHeight,scrollY:scrollY}})
console.log(JSON.stringify(info))
await pg.screenshot({path:'/tmp/v9-navcheck.png'})
await b.close()
