import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844}})).newPage()
pg.on('console',m=>{if(m.type()==='error')console.log('CONSOLE_ERR:',m.text().slice(0,200))})
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-b@naryadai.test'); await pg.fill('input[type=password]',process.env.PW_WORKERB)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/orders/638',{waitUntil:'networkidle'}); await pg.waitForTimeout(2500)
console.log('page text head:', (await pg.locator('body').innerText()).slice(0,200).replace(/\n/g,' | '))
const btn=pg.locator('button:has-text("Допуск оформлен")')
console.log('permit btn count:', await btn.count())
await btn.click(); await pg.waitForTimeout(400)
await pg.click('button:has-text("Отметить допуск")'); await pg.waitForTimeout(4000)
console.log('after permit:', (await pg.locator('body').innerText()).slice(0,300).replace(/\n/g,' | '))
await pg.screenshot({path:'/tmp/dbg-permit.png'})
await b.close()
