import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage()
pg.on('pageerror',e=>console.log('PAGEERROR:',e.message))
pg.on('console',m=>{if(m.type()==='error')console.log('CONSOLE:',m.text().slice(0,200))})
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-b@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERB)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/orders/646'); await pg.waitForTimeout(4000)
const n=await pg.evaluate(()=>document.querySelectorAll('input[type=checkbox]').length)
console.log('dom checkboxes:',n)
const labels=await pg.evaluate(()=>[...document.querySelectorAll('label')].map(l=>l.textContent.slice(0,40)))
console.log('labels:',JSON.stringify(labels))
await pg.evaluate(()=>window.scrollTo(0,document.body.scrollHeight))
await pg.waitForTimeout(600)
await pg.screenshot({path:'/tmp/dbg2-bottom.png'})
await b.close()
