import {chromium} from '@playwright/test'
const log=[]; const step=(n,ok,extra='')=>{log.push(`${ok?'PASS':'FAIL'} ${n}${extra?' :: '+extra:''}`); console.log(log[log.length-1])}
const b=await chromium.launch()
const dtop=await b.newContext({viewport:{width:1440,height:900}})
const mob=await b.newContext({viewport:{width:390,height:844}})
const HREF='/orders/638'
try{
  const w=await mob.newPage()
  await w.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
  await w.fill('input[type=email]','worker-b@naryadai.test'); await w.fill('input[type=password]',process.env.PW_WORKERB)
  await w.click('button:has-text("Войти")'); await w.waitForTimeout(7000)
  await w.goto('http://127.0.0.1:4173'+HREF,{waitUntil:'networkidle'}); await w.waitForTimeout(2500)
  const start=w.locator('button:has-text("Начать работу")')
  await start.waitFor({state:'visible',timeout:10000})
  await start.click()
  await w.locator('text=Закрытие наряда').waitFor({state:'visible',timeout:15000})
  step('work started, closure form visible', true)
  await w.fill('textarea','E2E: заменил сальник, проверил натяжение, протёков нет.')
  await w.selectOption('select',{index:1})
  await w.setInputFiles('input[type=file]','/tmp/e2e-photo.png'); await w.waitForTimeout(4000)
  const submit=w.locator('button:has-text("Отправить на проверку")')
  step('closure form valid (photo+text+code)', await submit.isEnabled())
  await w.screenshot({path:'/tmp/e2e-worker-closure.png'})
  await submit.click()
  await w.waitForTimeout(6000)
  const pg=await dtop.newPage()
  await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
  await pg.fill('input[type=email]','master@naryadai.test'); await pg.fill('input[type=password]',process.env.PW_MASTER)
  await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
  await pg.goto('http://127.0.0.1:4173'+HREF,{waitUntil:'networkidle'}); await pg.waitForTimeout(3000)
  const aiBtn=pg.locator('button:has-text("Проверить закрытие (ИИ)")')
  step('order in review state for master', await aiBtn.count()>0)
  if(await aiBtn.count()>0){
    await aiBtn.click()
    const got=await pg.waitForSelector('text=Карточка оснований',{timeout:90000}).then(()=>true).catch(()=>false)
    step('AI closure check returned card', got)
    if(got){
      const card=await pg.locator('body').innerText()
      const m=card.match(/Карточка оснований[\s\S]{0,120}/)
      step('AI card mode', true, (m?m[0]:'').replace(/\n/g,' | ').slice(0,150))
    }
    await pg.screenshot({path:'/tmp/e2e-master-ai.png'})
  }
  await pg.click('button:has-text("5")',{timeout:10000}); await pg.waitForTimeout(300)
  await pg.click('button:has-text("Закрыть наряд")'); await pg.waitForTimeout(5000)
  await pg.screenshot({path:'/tmp/e2e-master-closed.png'})
  await pg.goto('http://127.0.0.1:4173/closed',{waitUntil:'networkidle'}); await pg.waitForTimeout(3000)
  step('appears in Closed list', await pg.locator('text=E2E-ТЕСТ').count()>0)
}catch(e){step('EXCEPTION',false,String(e).slice(0,300))}
await b.close()
