import {chromium} from '@playwright/test'
const step=(n,ok,extra='')=>console.log(`${ok?'PASS':'FAIL'} ${n}${extra?' :: '+extra:''}`)
const b=await chromium.launch()
const dtop=await b.newContext({viewport:{width:1440,height:900}})
const mob=await b.newContext({viewport:{width:390,height:844}})
let orderHref=null
try{
  let pg=await dtop.newPage()
  await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
  await pg.fill('input[type=email]','master@naryadai.test'); await pg.fill('input[type=password]',process.env.PW_MASTER)
  await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
  await pg.goto('http://127.0.0.1:4173/issue',{waitUntil:'networkidle'}); await pg.waitForTimeout(2000)
  await pg.fill('textarea','E2E-ТЕСТ 2: полный цикл (удалить после демо)')
  const sels=pg.locator('select')
  await sels.nth(0).selectOption({index:1})
  await sels.nth(1).evaluate(el=>{const o=[...el.options].find(o=>o.text.includes('Демо-исполнитель')); el.value=o.value; el.dispatchEvent(new Event('change',{bubbles:true}))})
  await pg.click('button:has-text("Выдать наряд")'); await pg.waitForTimeout(4000)
  await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'}); await pg.waitForTimeout(3000)
  orderHref=await pg.locator('a',{hasText:'E2E-ТЕСТ 2'}).first().getAttribute('href')
  step('master issued order', !!orderHref, orderHref||'')
  const w=await mob.newPage()
  await w.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
  await w.fill('input[type=email]','worker-c@naryadai.test'); await w.fill('input[type=password]',process.env.PW_WORKERC)
  await w.click('button:has-text("Войти")'); await w.waitForTimeout(7000)
  step('worker-c login + sees order', await w.locator('text=E2E-ТЕСТ 2').count()>0)
  await w.goto('http://127.0.0.1:4173'+orderHref,{waitUntil:'networkidle'}); await w.waitForTimeout(2500)
  await w.click('button:has-text("Допуск подтверждён")'); await w.waitForTimeout(400)
  await w.fill('input[placeholder*="Номер допуска"]','Наряд-допуск №55, подтвердил мастер Петров')
  await w.click('button:has-text("Отметить допуск")')
  await w.locator('button:has-text("Принять назначение")').waitFor({state:'visible',timeout:15000})
  step('permit recorded', true)
  await w.click('button:has-text("Принять назначение")')
  await w.locator('button:has-text("Начать работу")').waitFor({state:'visible',timeout:15000})
  step('accepted', true)
  await w.click('button:has-text("Начать работу")')
  await w.locator('text=Закрытие наряда').waitFor({state:'visible',timeout:15000})
  step('work started, closure form', true)
  await w.fill('textarea','E2E: заменил сальник, проверил натяжение, протёков нет.')
  await w.selectOption('select',{index:1})
  await w.setInputFiles('input[type=file]','/tmp/e2e-photo.png'); await w.waitForTimeout(4000)
  const submit=w.locator('button:has-text("Отправить на проверку")')
  step('closure form valid', await submit.isEnabled())
  await submit.click(); await w.waitForTimeout(6000)
  step('submitted for review', true)
  await pg.goto('http://127.0.0.1:4173'+orderHref,{waitUntil:'networkidle'}); await pg.waitForTimeout(3000)
  const aiBtn=pg.locator('button:has-text("Проверить закрытие (ИИ)")')
  step('master sees review state', await aiBtn.count()>0)
  if(await aiBtn.count()>0){
    await aiBtn.click()
    const got=await pg.waitForSelector('text=Карточка оснований',{timeout:90000}).then(()=>true).catch(()=>false)
    step('AI closure check returned', got)
    if(got){const t=await pg.locator('body').innerText(); const m=t.match(/Карточка оснований[\s\S]{0,140}/); step('AI card',true,(m?m[0]:'').replace(/\n/g,' | ').slice(0,160))}
    await pg.screenshot({path:'/tmp/e2e-master-ai.png'})
  }
  await pg.click('button:has-text("5")',{timeout:10000}); await pg.waitForTimeout(300)
  await pg.click('button:has-text("Закрыть наряд")'); await pg.waitForTimeout(5000)
  await pg.goto('http://127.0.0.1:4173/closed',{waitUntil:'networkidle'}); await pg.waitForTimeout(3000)
  step('closed + listed', await pg.locator('text=E2E-ТЕСТ 2').count()>0)
  await pg.screenshot({path:'/tmp/e2e-master-closed.png'})
}catch(e){step('EXCEPTION',false,String(e).slice(0,250))}
console.log('ORDER_HREF='+orderHref)
await b.close()
