import type{Plugin}from'vite'
// Serve-only isolated local DB harness, never production.
export function localCycleFixture():Plugin{return{name:'local-cycle-test',apply:'serve',enforce:'pre',transform(_code,id){if(!process.env.TEKTON_LOCAL_CYCLE_PORT||!id.endsWith('/src/lib/data.ts'))return null;const port=Number(process.env.TEKTON_LOCAL_CYCLE_PORT);return{code:`
const root='http://127.0.0.1:${port}';const role=new URLSearchParams(location.search).get('role')||'worker';
async function call(path,body){const r=await fetch(root+path,{method:body?'POST':'GET',headers:{'content-type':'application/json'},body:body?JSON.stringify({...body,role}):undefined});const x=await r.json();if(!r.ok)throw Error(x.error||'Local request failed');return x}
export const supabase=null;export const restoreSession=async()=>true;export const state=()=>call('/app-state?role='+role);export const logout=async()=>{};export const login=async()=>{};
export const watch=(fn,status)=>{status(true);const timer=setInterval(fn,2000);return()=>clearInterval(timer)};export const watchNotifications=()=>()=>{};export const reviewArchiveReceipt=()=>null;
export const transition=async(id,x)=>{if(x.status==='ai_review')return call('/app-review',{id,version:x.version});let closure=x.closure;if(x.status==='completed'){const evidence=[];for(const uri of closure.photos){const binary=await(await fetch(uri)).blob();const r=await fetch(root+'/api/canonical-photo/'+id,{method:'POST',headers:{authorization:'Bearer synthetic-worker-session','x-order-version':String(x.version)},body:binary});const e=await r.json();if(!r.ok)throw Error(e.error);evidence.push(e)}closure={...closure,photos:evidence.map(e=>e.canonical)}}return call('/app-transition',{id,...x,closure})};
export const createOrder=x=>call('/app-create',x);export const recordPermit=(id,x)=>call('/app-permit',{id,...x});export const startWork=(id,version,texts)=>call('/app-start',{id,version,texts});export const recordEquipmentState=(id,state,reason)=>call('/app-equipment',{id,state,reason});
export const recordDeclarations=(id,phase,texts)=>call('/app-declarations',{id,phase,texts});export const manualMasterDecision=(id,version,decision,score,reason,failure)=>call('/app-manual',{id,version,decision,score,reason,failure});
const blocked=async()=>{throw Error('Not implemented in isolated local cycle harness')};export const manageOrder=blocked,recordIntakePhoto=blocked,assistantChat=blocked,repeatCheck=blocked,recordLateDeclarations=blocked;
export const repairMemory=async()=>[],repeatTop=async()=>[],ratings=(since,until)=>call('/app-rating?role='+role+'&since='+encodeURIComponent(since)+'&until='+encodeURIComponent(until)),anomalies=async()=>[],refusalReviews=async()=>[],closedReportOrders=async()=>{const s=await state();return s.orders.filter(o=>o.status==='closed')},knowledgeDocs=async()=>[];export const reviewRefusal=(id,classification,note)=>call('/app-review-refusal',{id,classification,note}),reviewRepairMemory=blocked,reviewKnowledge=blocked,submitKnowledge=blocked;export const telegramPairStatus=async()=>({enabled:false});export const beginTelegramPair=blocked,confirmTelegramPair=blocked,disconnectTelegramPair=blocked;
`,map:null}}}}
