import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-a@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERA)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/assistant'); await pg.waitForTimeout(2000)
await pg.fill('input.tk-input', 'Какая смазка применяется для конвейера К-3?')
await pg.keyboard.press('Enter'); await pg.waitForTimeout(15000)
await pg.screenshot({path:'/tmp/v12-11-assistant-live.png',fullPage:true})
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(1500)
await pg.screenshot({path:'/tmp/v12-12-settings-dark.png'})
const light=pg.locator('button:has-text("Светлая")')
if(await light.count()){await light.click(); await pg.waitForTimeout(800)}
await pg.screenshot({path:'/tmp/v12-13-settings-light.png'})
await pg.goto('http://127.0.0.1:4173/'); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v12-14-home-light.png'})
await pg.goto('http://127.0.0.1:4173/orders/532'); await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/v12-15-order-light.png',fullPage:true})
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(1200)
const big=pg.locator('button:has-text("160%")'); if(await big.count()) await big.click()
const glove=pg.locator('button:has-text("Перчатки")'); if(await glove.count()) await glove.click()
await pg.waitForTimeout(800)
await pg.goto('http://127.0.0.1:4173/'); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v12-16-scale160-glove.png'})
await b.close(); console.log('done')
