import {chromium} from '@playwright/test'
const b=await chromium.launch()
const mk=()=>b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})
const login=async(pg,email,pw)=>{await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});await pg.fill('input[type=email]',email);await pg.fill('input[type=password]',pw);await pg.click('button:has-text("Войти")');await pg.waitForTimeout(7000)}
// ---- PART A: story on #649 (worker-e2e) with synthetic fixtures ----
let pg=await (await mk()).newPage()
await login(pg,'worker-e2e@naryadai.test','E2eWorker-2026!')
await pg.goto('http://127.0.0.1:4173/orders/649'); await pg.waitForTimeout(4500)
await pg.screenshot({path:'/tmp/v12-01-issued.png'})
await pg.click('button:has-text("Не требуется")'); await pg.waitForTimeout(500)
await pg.click('button:has-text("Отметить допуск")'); await pg.waitForTimeout(2500)
await pg.click('button:has-text("Принять назначение")'); await pg.waitForTimeout(3000)
await pg.evaluate(()=>window.scrollTo(0,0)); await pg.waitForTimeout(400)
await pg.setInputFiles('input[type=file]', 'scripts/fixtures/fixture-intake.png'); await pg.waitForTimeout(5000)
await pg.screenshot({path:'/tmp/v12-02-intake-fixture.png',fullPage:true})
const cbs=pg.locator('input[type=checkbox]')
for(let i=0;i<await cbs.count();i++) await cbs.nth(i).click()
await pg.evaluate(()=>window.scrollTo(0,document.body.scrollHeight)); await pg.waitForTimeout(400)
await pg.screenshot({path:'/tmp/v12-03-gate.png'})
await pg.click('button:has-text("Подтвердить и начать работу")'); await pg.waitForTimeout(4000)
await pg.evaluate(()=>window.scrollTo(0,0)); await pg.waitForTimeout(400)
await pg.screenshot({path:'/tmp/v12-04-in-progress.png',fullPage:true})
await pg.click('button:has-text("Сдать наряд")'); await pg.waitForTimeout(1000)
await pg.screenshot({path:'/tmp/v12-05-wizard-recorded.png'})
await pg.click('button:has-text("Далее")'); await pg.waitForTimeout(500)
await pg.click('button:has-text("Шаблон 1")')
await pg.locator('.fixed select').selectOption({index:1})
await pg.locator('.fixed input[type=checkbox]').last().click(); await pg.waitForTimeout(300)
await pg.screenshot({path:'/tmp/v12-06-wizard-report.png'})
await pg.click('button:has-text("Далее")'); await pg.waitForTimeout(500)
await pg.setInputFiles('.fixed input[type=file]', 'scripts/fixtures/fixture-after.png'); await pg.waitForTimeout(2000)
await pg.screenshot({path:'/tmp/v12-07-wizard-photos.png'})
await pg.click('button:has-text("На проверку мастеру")'); await pg.waitForTimeout(6000)
await pg.screenshot({path:'/tmp/v12-08-submitted.png',fullPage:true})
await pg.close()
// ---- PART B: static screens (worker-a) ----
pg=await (await mk()).newPage()
await login(pg,'worker-a@naryadai.test',process.env.PW_WORKERA)
await pg.screenshot({path:'/tmp/v12-09-home-dark.png'})
await pg.goto('http://127.0.0.1:4173/orders'); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v12-10-orders-dark.png'})
await pg.goto('http://127.0.0.1:4173/assistant'); await pg.waitForTimeout(2000)
await pg.fill('textarea, input[type=text]', 'Какая смазка применяется для конвейера К-3?')
await pg.keyboard.press('Enter'); await pg.waitForTimeout(12000)
await pg.screenshot({path:'/tmp/v12-11-assistant-live.png',fullPage:true})
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(1500)
await pg.screenshot({path:'/tmp/v12-12-settings-dark.png'})
// light theme
await pg.click('button:has-text("Светлая")'); await pg.waitForTimeout(800)
await pg.screenshot({path:'/tmp/v12-13-settings-light.png'})
await pg.goto('http://127.0.0.1:4173/'); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v12-14-home-light.png'})
await pg.goto('http://127.0.0.1:4173/orders/532'); await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/v12-15-order-light.png',fullPage:true})
// scale 160 + glove
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(1200)
const big=pg.locator('button:has-text("160%")')
if(await big.count()) await big.click()
const glove=pg.locator('button:has-text("Перчатки")')
if(await glove.count()) await glove.click()
await pg.waitForTimeout(800)
await pg.goto('http://127.0.0.1:4173/'); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v12-16-scale160-glove.png'})
await b.close(); console.log('pack done')
