import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-a@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERA)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(1500)
await pg.click('button:has-text("ОГРОМНЫЙ")'); await pg.waitForTimeout(400)
await pg.locator('div:has-text("РЕЖИМ ПЕРЧАТОК") ~ button:has-text("ВКЛ"), button:has-text("ВКЛ")').first().click(); await pg.waitForTimeout(600)
await pg.screenshot({path:'/tmp/v12-16b-settings-huge-glove.png'})
await pg.goto('http://127.0.0.1:4173/'); await pg.waitForTimeout(7000)
await pg.screenshot({path:'/tmp/v12-16-scale160-glove.png'})
await b.close(); console.log('done')
