import {chromium} from '@playwright/test'
const b=await chromium.launch()
const mk=()=>b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})
const login=async(pg,email,pw)=>{await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});await pg.fill('input[type=email]',email);await pg.fill('input[type=password]',pw);await pg.click('button:has-text("Войти")');await pg.waitForTimeout(7000)}
let pg=await (await mk()).newPage()
await login(pg,'worker-a@naryadai.test',process.env.PW_WORKERA)
await pg.screenshot({path:'/tmp/v13-01-home.png'})
await pg.goto('http://127.0.0.1:4173/orders'); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v13-02-orders.png'})
await pg.goto('http://127.0.0.1:4173/orders/532'); await pg.waitForTimeout(4000)
await pg.evaluate(()=>window.scrollTo(0,0)); await pg.waitForTimeout(300)
await pg.screenshot({path:'/tmp/v13-03-order.png',fullPage:true})
await pg.click('button:has-text("Сдать наряд")'); await pg.waitForTimeout(800)
const cbs=pg.locator('.fixed input[type=checkbox]')
for(let i=0;i<await cbs.count();i++) await cbs.nth(i).click()
await pg.click('button:has-text("Далее")'); await pg.waitForTimeout(500)
await pg.screenshot({path:'/tmp/v13-04-wizard-report.png'})
await pg.keyboard.press('Escape')
await pg.goto('http://127.0.0.1:4173/assistant'); await pg.waitForTimeout(2000)
await pg.fill('input.tk-input','Какая смазка применяется для конвейера К-3?')
await pg.keyboard.press('Enter'); await pg.waitForTimeout(15000)
await pg.screenshot({path:'/tmp/v13-05-assistant.png'})
await pg.close()
pg=await (await mk()).newPage()
await login(pg,'worker-b@naryadai.test',process.env.PW_WORKERB)
await pg.goto('http://127.0.0.1:4173/orders/646'); await pg.waitForTimeout(4500)
await pg.evaluate(()=>window.scrollTo(0,document.body.scrollHeight)); await pg.waitForTimeout(400)
await pg.screenshot({path:'/tmp/v13-06-gate.png'})
await b.close(); console.log('done')
