import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-e2e@naryadai.test')
await pg.fill('input[type=password]','E2eWorker-2026!')
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/orders/650'); await pg.waitForTimeout(4500)
await pg.screenshot({path:'/tmp/v12-01-issued.png'})
await pg.click('button:has-text("Не требуется")'); await pg.waitForTimeout(500)
await pg.click('button:has-text("Отметить допуск")'); await pg.waitForTimeout(2500)
await pg.click('button:has-text("Принять назначение")'); await pg.waitForTimeout(3000)
await pg.setInputFiles('input[type=file]', 'scripts/fixtures/fixture-intake.png')
await pg.waitForSelector('img[alt="Фото до"]',{timeout:20000})
await pg.waitForTimeout(1500)
await pg.evaluate(()=>window.scrollTo(0,0)); await pg.waitForTimeout(400)
await pg.screenshot({path:'/tmp/v12-02-intake-fixture.png'})
const cbs=pg.locator('input[type=checkbox]')
for(let i=0;i<await cbs.count();i++) await cbs.nth(i).click()
await pg.evaluate(()=>window.scrollTo(0,document.body.scrollHeight)); await pg.waitForTimeout(500)
await pg.screenshot({path:'/tmp/v12-03-gate.png'})
await pg.click('button:has-text("Подтвердить и начать работу")'); await pg.waitForTimeout(4000)
await pg.evaluate(()=>window.scrollTo(0,0)); await pg.waitForTimeout(400)
await pg.screenshot({path:'/tmp/v12-04-in-progress.png',fullPage:true})
await pg.click('button:has-text("Сдать наряд")'); await pg.waitForTimeout(1000)
await pg.screenshot({path:'/tmp/v12-05-wizard-recorded.png'})
await pg.click('button:has-text("Далее")'); await pg.waitForTimeout(500)
await pg.click('button:has-text("Шаблон 1")')
await pg.locator('.fixed select').selectOption({index:1})
await pg.locator('.fixed input[type=checkbox]').last().click(); await pg.waitForTimeout(300)
await pg.screenshot({path:'/tmp/v12-06-wizard-report.png'})
await pg.click('button:has-text("Далее")'); await pg.waitForTimeout(500)
await pg.setInputFiles('.fixed input[type=file]', 'scripts/fixtures/fixture-after.png')
await pg.waitForSelector('.fixed img[alt="После"]',{timeout:20000})
await pg.waitForTimeout(800)
await pg.screenshot({path:'/tmp/v12-07-wizard-photos.png'})
await pg.click('button:has-text("На проверку мастеру")'); await pg.waitForTimeout(6000)
await pg.evaluate(()=>window.scrollTo(0,0)); await pg.waitForTimeout(400)
await pg.screenshot({path:'/tmp/v12-08-submitted.png',fullPage:true})
await b.close(); console.log('done')
