import {chromium} from 'playwright'
const prefix=process.argv[2]
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2})).newPage()
await pg.goto('http://127.0.0.1:4173/login')
await pg.fill('input[type=email]','worker-a@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERA)
await pg.click('button:has-text("Войти")')
await pg.waitForSelector('text=ОСТАЛОСЬ',{timeout:20000}).catch(()=>{})
await pg.waitForTimeout(2500)
await pg.screenshot({path:`/tmp/${prefix}-dark-home.png`})
await pg.goto('http://127.0.0.1:4173/orders'); await pg.waitForTimeout(2000)
await pg.screenshot({path:`/tmp/${prefix}-dark-inactive.png`})
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(2500)
await pg.click('button:has-text("Светлая")'); await pg.waitForTimeout(1500)
await pg.goto('http://127.0.0.1:4173/')
await pg.waitForSelector('text=ОСТАЛОСЬ',{timeout:20000}).catch(()=>{})
await pg.waitForTimeout(2500)
await pg.screenshot({path:`/tmp/${prefix}-light-home.png`})
await pg.goto('http://127.0.0.1:4173/orders'); await pg.waitForTimeout(2000)
await pg.screenshot({path:`/tmp/${prefix}-light-inactive.png`})
await b.close()
console.log('done '+prefix)
