import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage()
const shot=(n)=>pg.screenshot({path:'/tmp/v9-'+n+'.png'})
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-a@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERA)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await shot('01-dark-home')
await pg.locator('header button:has-text("AI")').first().click(); await pg.waitForTimeout(900); await shot('15-voice-hud')
await pg.locator('.fixed button').last().click(); await pg.waitForTimeout(400)
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(800)
await pg.click('button:has-text("Вкл")'); await pg.click('button:has-text("Огромный")'); await pg.waitForTimeout(400)
await pg.goto('http://127.0.0.1:4173/'); await pg.waitForTimeout(2000); await shot('11-scale160-home')
await b.close(); console.log('done')
