import {chromium} from 'playwright'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:1440,height:1400}})).newPage()
await pg.goto('http://localhost:4173/login')
await pg.fill('input[type=email]','master@naryadai.test');await pg.fill('input[type=password]',process.env.PW_MASTER)
await pg.click('button:has-text("Войти")');await pg.waitForSelector('a[href="/report"]',{timeout:30000})
await pg.goto('http://localhost:4173/report');await pg.waitForTimeout(9000)
await pg.screenshot({path:'/tmp/master-report.png',fullPage:false})
await pg.evaluate(()=>window.scrollTo(0,document.body.scrollHeight*0.32));await pg.waitForTimeout(800)
await pg.screenshot({path:'/tmp/master-report-mid.png',fullPage:false})
console.log('done')
await b.close()
