import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage()
pg.on('pageerror',e=>console.log('PAGEERROR',String(e).slice(0,200)))
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-a@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERA)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/orders/532'); await pg.waitForTimeout(2500)
// intake photo upload
await pg.setInputFiles('.tk-card input[type=file]', '/tmp/ref-02-dark-work.png')
await pg.waitForTimeout(6000)
await pg.screenshot({path:'/tmp/v9-20-intake.png'})
// wizard: step1 (2 decls), step2 with post-work decl, step3 shows BEFORE readonly
const btn=pg.locator('button:has-text("Сдать наряд")').first()
await btn.click(); await pg.waitForTimeout(700); await pg.screenshot({path:'/tmp/v9-21-wizard-step1.png'})
const cbs=pg.locator('.fixed input[type=checkbox]')
for(let i=0;i<await cbs.count();i++) await cbs.nth(i).click()
await pg.click('button:has-text("Далее")'); await pg.waitForTimeout(400)
await pg.click('button:has-text("Шаблон 1")'); await pg.locator('.fixed select').selectOption({index:1})
await pg.locator('.fixed input[type=checkbox]').last().click(); await pg.waitForTimeout(300)
await pg.screenshot({path:'/tmp/v9-22-wizard-step2.png'})
await pg.click('button:has-text("Далее")'); await pg.waitForTimeout(400)
await pg.screenshot({path:'/tmp/v9-23-wizard-step3.png'})
await b.close(); console.log('done')
