import {chromium} from '@playwright/test'
const b=await chromium.launch()
// worker mobile
let ctx=await b.newContext({viewport:{width:390,height:844}})
let pg=await ctx.newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-a@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERA)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/orders/532',{waitUntil:'networkidle'}); await pg.waitForTimeout(2500)
await pg.evaluate(()=>window.scrollTo(0,document.body.scrollHeight)); await pg.waitForTimeout(800)
await pg.screenshot({path:'/tmp/v8-03b-detail-bottom.png'})
await pg.screenshot({path:'/tmp/v8-03c-detail-full.png',fullPage:true})
await pg.goto('http://127.0.0.1:4173/profile',{waitUntil:'networkidle'}); await pg.waitForTimeout(1500)
await pg.evaluate(()=>window.scrollTo(0,document.body.scrollHeight)); await pg.waitForTimeout(500)
await pg.screenshot({path:'/tmp/v8-04-profile.png'})
await ctx.close()
// master desktop
ctx=await b.newContext({viewport:{width:1440,height:900}})
pg=await ctx.newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','master@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_MASTER)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/orders/597',{waitUntil:'networkidle'}); await pg.waitForTimeout(2500)
await pg.evaluate(()=>window.scrollTo(0,600)); await pg.waitForTimeout(500)
await pg.screenshot({path:'/tmp/v8m-03-detail.png'})
await pg.goto('http://127.0.0.1:4173/review',{waitUntil:'networkidle'}); await pg.waitForTimeout(2000)
await pg.screenshot({path:'/tmp/v8m-02-review.png'})
await pg.goto('http://127.0.0.1:4173/issue',{waitUntil:'networkidle'}); await pg.waitForTimeout(2000)
await pg.screenshot({path:'/tmp/v8m-06-issue.png'})
await b.close(); console.log('done')
