import {chromium} from 'playwright'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:1600,height:1000}})).newPage()
await pg.goto('http://127.0.0.1:4173/login');await pg.screenshot({path:'/tmp/brand-login.png'})
await pg.fill('input[type=email]','master@naryadai.test');await pg.fill('input[type=password]',process.env.PW_MASTER);await pg.click('button:has-text("Войти")')
await pg.waitForSelector('aside',{timeout:30000});await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'}).catch(()=>{})
await pg.waitForTimeout(2500);await pg.screenshot({path:'/tmp/brand-board-unfiltered.png'})
await pg.locator('label:has-text("Скрыть технические") input').check();await pg.waitForTimeout(600);await pg.screenshot({path:'/tmp/brand-board-filtered.png'})
const pg2=await (await b.newContext({viewport:{width:430,height:932}})).newPage()
await pg2.goto('http://127.0.0.1:4173/login');await pg2.fill('input[type=email]','worker-a@naryadai.test');await pg2.fill('input[type=password]',process.env.PW_WORKERA);await pg2.click('button:has-text("Войти")')
await pg2.waitForTimeout(4000);await pg2.screenshot({path:'/tmp/brand-worker.png'})
await b.close();console.log('done')
