import {chromium} from '@playwright/test'
const b=await chromium.launch()
const ctx=await b.newContext({viewport:{width:390,height:844}})
const pg=await ctx.newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'}); await pg.waitForTimeout(1500)
await pg.screenshot({path:'/tmp/v8-00-login.png'})
await pg.fill('input[type=email]','master@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_MASTER)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.setViewportSize({width:1440,height:900})
await pg.goto('http://127.0.0.1:4173/issue',{waitUntil:'networkidle'}); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v8m-06-issue.png'})
await pg.goto('http://127.0.0.1:4173/closed',{waitUntil:'networkidle'}); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v8m-07-closed.png'})
await b.close(); console.log('done')
