import {chromium} from 'playwright'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:1440,height:900}})).newPage()
await pg.goto('http://localhost:4173/login')
await pg.fill('input[type=email]','leader@naryadai.test');await pg.fill('input[type=password]',process.env.PW_LEADER)
await pg.click('button:has-text("Войти")');await pg.waitForTimeout(9000)
await pg.screenshot({path:'/tmp/role-leader.png'})
await pg.setViewportSize({width:390,height:844});await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/role-leader-phone.png'})
console.log('done')
await b.close()
