import {chromium} from 'playwright'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:1440,height:900}})).newPage()
await pg.goto('http://127.0.0.1:4173/login')
await pg.fill('input[type=email]','master@naryadai.test'); await pg.fill('input[type=password]',process.env.PW_MASTER)
await pg.click('button:has-text("Войти")')
await pg.waitForSelector('text=Исполнители смены',{timeout:30000}).catch(()=>{})
await pg.waitForTimeout(3500)
await pg.screenshot({path:'/tmp/p0-board-crew.png'})
await pg.click('button:has-text("Канбан")')
await pg.waitForTimeout(1500)
await pg.screenshot({path:'/tmp/p0-board-kanban.png',fullPage:true})
await pg.goto('http://127.0.0.1:4173/report',{waitUntil:'networkidle'}).catch(()=>{})
await pg.waitForSelector('text=пять факторов',{timeout:30000}).catch(()=>{})
await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/p0-report-rating.png',fullPage:true})
await pg.goto('http://127.0.0.1:4173/issue',{waitUntil:'networkidle'}).catch(()=>{})
await pg.waitForTimeout(2500)
await pg.selectOption('select >> nth=0',{index:1}).catch(()=>{})
await pg.waitForTimeout(1200)
await pg.screenshot({path:'/tmp/p0-issue-hint.png'})
await pg.context().close()
const pg2=await (await b.newContext({viewport:{width:430,height:932}})).newPage()
await pg2.goto('http://127.0.0.1:4173/login')
await pg2.fill('input[type=email]','worker-a@naryadai.test'); await pg2.fill('input[type=password]',process.env.PW_WORKERA)
await pg2.click('button:has-text("Войти")')
await pg2.waitForTimeout(5000)
await pg2.goto('http://127.0.0.1:4173/profile',{waitUntil:'networkidle'}).catch(()=>{})
await pg2.waitForTimeout(3500)
await pg2.screenshot({path:'/tmp/p0-profile-rating.png'})
await b.close(); console.log('done')
