import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:1440,height:900}})).newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','admin@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_ADMIN)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(8000)
await pg.screenshot({path:'/tmp/v8a-01-admin.png'})
await pg.goto('http://127.0.0.1:4173/report',{waitUntil:'networkidle'}); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v8a-02-admin-report.png'})
await b.close(); console.log('done')
