import {chromium} from 'playwright'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:1440,height:1100}})).newPage()
await pg.goto('http://localhost:4173/login')
await pg.fill('input[type=email]','master@naryadai.test');await pg.fill('input[type=password]',process.env.PW_MASTER)
await pg.click('button:has-text("Войти")');await pg.waitForSelector('a[href="/report"]',{timeout:30000})
await pg.goto('http://localhost:4173/issue')
await pg.locator('select').nth(0).selectOption({index:1})
await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/issue-dispatch.png',fullPage:true})
console.log('shot saved')
await b.close()
