import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-e2e@naryadai.test')
await pg.fill('input[type=password]','E2eWorker-2026!')
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/orders/'+process.env.OID); await pg.waitForTimeout(4500)
await pg.screenshot({path:'/tmp/v13-07-permit.png'})
await pg.click('button:has-text("Не требуется")'); await pg.waitForTimeout(500)
await pg.click('button:has-text("Отметить допуск")'); await pg.waitForTimeout(2500)
await pg.click('button:has-text("Принять назначение")'); await pg.waitForTimeout(3000)
await pg.evaluate(()=>window.scrollTo(0,document.body.scrollHeight)); await pg.waitForTimeout(500)
await pg.screenshot({path:'/tmp/v13-06-gate.png'})
await b.close(); console.log('done')
