import {chromium} from '@playwright/test'
const b=await chromium.launch()
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-a@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERA)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(2500)
const btn=pg.locator('button:has-text("Светлая"), button:has-text("Светл")').first()
if(await btn.count()) await btn.click(); await pg.waitForTimeout(1200)
await pg.goto('http://127.0.0.1:4173/'); await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/v14-03-home-light.png'})
await pg.goto('http://127.0.0.1:4173/assistant'); await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/v14-04-assistant-light.png'})
await b.close(); console.log('done')
