import {chromium} from '@playwright/test'
const b=await chromium.launch()
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})
const pg=await ctx.newPage()
// fresh visitor => default scale applies
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-a@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERA)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
await pg.screenshot({path:'/tmp/v16-01-dark-home.png'})
await pg.goto('http://127.0.0.1:4173/orders'); await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/v16-02-dark-orders.png'})
await pg.goto('http://127.0.0.1:4173/orders/532'); await pg.waitForTimeout(3500)
await pg.screenshot({path:'/tmp/v16-03-dark-order.png'})
await pg.goto('http://127.0.0.1:4173/assistant'); await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/v16-04-dark-assistant.png'})
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v16-05-dark-settings.png'})
const btn=pg.locator('button:has-text("Светлая"), button:has-text("Светл")').first()
if(await btn.count()) await btn.click(); await pg.waitForTimeout(1200)
await pg.goto('http://127.0.0.1:4173/'); await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/v16-06-light-home.png'})
await b.close(); console.log('done')
