import {chromium} from '@playwright/test'
const b=await chromium.launch()
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})
const pg=await ctx.newPage()
await pg.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'})
await pg.fill('input[type=email]','worker-a@naryadai.test')
await pg.fill('input[type=password]',process.env.PW_WORKERA)
await pg.click('button:has-text("Войти")'); await pg.waitForTimeout(7000)
// switch to light theme
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(2500)
await pg.click('button:has-text("Светлая")'); await pg.waitForTimeout(1200)
await pg.goto('http://127.0.0.1:4173/orders'); await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/v18-01-light-orders.png'})
await pg.goto('http://127.0.0.1:4173/orders/532'); await pg.waitForTimeout(3500)
await pg.screenshot({path:'/tmp/v18-02-light-order.png'})
await pg.goto('http://127.0.0.1:4173/assistant'); await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/v18-03-light-assistant.png'})
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(2500)
await pg.screenshot({path:'/tmp/v18-04-light-settings.png'})
// back to dark for scroll-bottom + glove
await pg.click('button:has-text("Тёмная")'); await pg.waitForTimeout(1200)
await pg.goto('http://127.0.0.1:4173/orders/532'); await pg.waitForTimeout(3500)
await pg.evaluate(()=>{const m=document.querySelector('main'); m.scrollTo(0,m.scrollHeight)})
await pg.waitForTimeout(800)
await pg.screenshot({path:'/tmp/v18-05-dark-order-bottom.png'})
// glove mode ON (160% scale still default)
await pg.goto('http://127.0.0.1:4173/settings'); await pg.waitForTimeout(2500)
const gloveCard=pg.locator('div.tk-card', {hasText:'РЕЖИМ ПЕРЧАТОК'}).first()
await gloveCard.locator('button', {hasText:'ВКЛ'}).click(); await pg.waitForTimeout(1200)
await pg.goto('http://127.0.0.1:4173/'); await pg.waitForTimeout(3000)
await pg.screenshot({path:'/tmp/v18-06-dark-glove-home.png'})
await pg.goto('http://127.0.0.1:4173/orders/532'); await pg.waitForTimeout(3500)
await pg.evaluate(()=>{const m=document.querySelector('main'); m.scrollTo(0,m.scrollHeight)})
await pg.waitForTimeout(800)
await pg.screenshot({path:'/tmp/v18-07-dark-glove-order-bottom.png'})
await b.close()
console.log('done')
