import{spawn}from'node:child_process';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{chromium}from'@playwright/test';import pg from'pg';import assert from'node:assert/strict';
const children=[];const results=[];const wait=ms=>new Promise(r=>setTimeout(r,ms));
function start(bin,args){const p=spawn(bin,args,{stdio:['ignore','pipe','pipe']});children.push(p);p.stdout.on('data',x=>process.stdout.write(x));p.stderr.on('data',x=>process.stderr.write(x));return p}
async function run(bin,args){const p=spawn(bin,args,{stdio:'inherit'});await new Promise((res,rej)=>{p.on('exit',c=>c===0?res():rej(Error(bin+' failed '+c)));p.on('error',rej)})}
let browser;try{
start('node',['scripts/database.mjs']);
let ready=false;for(let i=0;i<40;i++){await wait(500);try{const c=new pg.Client({host:'127.0.0.1',port:5433,user:'postgres',password:readFileSync('.local/db-secret','utf8'),database:'naryadai'});await c.connect();await c.end();ready=true;break}catch{}}
if(!ready)throw Error('PostgreSQL startup failed');
await run('node',['scripts/seed.mjs']);await run('node',['tests/database-checks.mjs']);await run('node',['scripts/history-seed.mjs']);start('node',['server/index.mjs']);start(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5173']);
for(let i=0;i<30;i++){await wait(500);try{if((await fetch('http://127.0.0.1:5173')).ok)break}catch{}}
browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const master=await browser.newContext({viewport:{width:1440,height:1000}});const worker=await browser.newContext({viewport:{width:390,height:844}});const other=await browser.newContext();
const m=await master.newPage(),w=await worker.newPage();m.setDefaultTimeout(7000);w.setDefaultTimeout(7000);m.on('console',msg=>{if(msg.type()==='error')console.error('Browser console:',msg.text())});m.on('response',r=>{if(r.url().includes('/api/orders'))console.log('ORDER HTTP',r.status(),r.url())});await m.goto('http://127.0.0.1:5173');await m.getByRole('button',{name:'Мастер смены Мастер смены'}).click();await m.getByRole('heading',{name:'Наряды смены'}).waitFor();
await w.goto('http://127.0.0.1:5173');await w.getByRole('button',{name:'Исполнитель А Исполнитель'}).click();await w.getByRole('heading',{name:'Наряды смены'}).waitFor();
async function request(ctx,path,data){const r=await ctx.request.post('http://127.0.0.1:5173/api'+path,{data});return {status:r.status(),body:await r.json()}}
await other.request.post('http://127.0.0.1:5173/api/demo-login',{data:{employee_id:'00000000-0000-4000-8000-000000000004'}});
const title='Заменить подшипник · тест '+Math.floor(Date.now()/1000)%10000;const startedAt=performance.now();await m.getByRole('button',{name:'Выдать наряд',exact:true}).click();await m.getByLabel('Проблема и работы').fill(title);await m.getByLabel('Исполнитель',{exact:true}).selectOption('00000000-0000-4000-8000-000000000002');await m.getByRole('button',{name:'Выдать',exact:true}).click();await m.getByRole('heading',{name:title}).waitFor();const afterCreate=await(await master.request.get('http://127.0.0.1:5173/api/state')).json();const id=afterCreate.orders.find(o=>o.title===title).id;
await w.getByRole('heading',{name:title}).waitFor();const realtimeMs=Math.round(performance.now()-startedAt);results.push(`New order appeared in second browser context through PostgreSQL LISTEN/NOTIFY + SSE: ${realtimeMs} ms (local machine, not phone/network SLA)`);
let state=await(await other.request.get('http://127.0.0.1:5173/api/state')).json();assert.ok(!state.orders.some(o=>o.id===id));results.push('RLS: unrelated worker cannot read new order');
const forbidden=await request(other,`/orders/${id}/transition`,{status:'accepted',version:1});assert.equal(forbidden.status,400);results.push('RLS: unrelated worker cannot mutate new order');
const leader=await browser.newContext();await leader.request.post('http://127.0.0.1:5173/api/demo-login',{data:{employee_id:'00000000-0000-4000-8000-000000000003'}});assert.equal((await request(leader,'/orders',{title:'forbidden',kind:'planned',equipment_id:1,assignee_id:'00000000-0000-4000-8000-000000000002',priority:'normal',deadline:new Date().toISOString()})).status,400);results.push('RLS: leader cannot issue an order');
const jump=await request(worker,`/orders/${id}/transition`,{status:'closed',version:1});assert.equal(jump.status,400);results.push('Invalid status jump rejected');
await w.getByRole('heading',{name:title}).click();await w.getByRole('button',{name:'Принять в работу',exact:true}).click();await w.getByRole('button',{name:'Начать исполнение',exact:true}).click();await w.getByRole('heading',{name:'Исполнено: заполните закрытие'}).waitFor();
const missing=await request(worker,`/orders/${id}/transition`,{status:'completed',version:3,closure:{works:'Заменён подшипник, выполнена проверка',fault_code:'М-02',materials:[],photos:[]}});assert.equal(missing.status,400);results.push('Unplanned closure without after-photo rejected');
const stale=await request(worker,`/orders/${id}/transition`,{status:'paused',version:1,reason:'Ждём запчасти'});assert.equal(stale.status,400);results.push('Stale version rejected');
await w.getByLabel('Выполненные работы').fill('Заменён подшипник, проверены крепления и соосность привода');
// Synthetic image only, not evidence of physical repair.
const photo=await browser.newPage({viewport:{width:480,height:320}});await photo.setContent('<body style="background:#e8e4dc;font:24px Arial;padding:50px"><h2>Синтетическое фото</h2><p>Тест закрытия наряда</p><div style="width:180px;height:70px;background:#555;border-radius:10px"></div></body>');await photo.screenshot({path:'.local/synthetic-photo.png'});await photo.close();await w.locator('input[type=file]').setInputFiles('.local/synthetic-photo.png');await w.getByAltText('Фото после ремонта',{exact:true}).waitFor();
mkdirSync('/downloads/slice-evidence',{recursive:true});await w.screenshot({path:'/downloads/slice-evidence/worker-closure.png',fullPage:true});
await w.getByRole('button',{name:'Отправить на проверку'}).click();await w.getByRole('heading',{name:'Закрытие исполнителя'}).waitFor();await m.getByRole('heading',{name:title}).click();await m.getByRole('button',{name:'Проверить закрытие'}).click();await m.getByRole('heading',{name:'Карточка оснований'}).waitFor();await m.getByRole('button',{name:'Мастер подтверждает'}).click();await m.locator('.badge.closed').waitFor();results.push('UI cycle: issue -> accept -> start -> completed -> review -> master closure passed');
await m.getByRole('button',{name:'История оборудования',exact:true}).click();await m.getByRole('heading',{name:'Ремонтный след: Конвейер К-3'}).waitFor();await m.screenshot({path:'/downloads/slice-evidence/equipment-history.png',fullPage:true});await m.getByRole('button',{name:'Скрыть историю'}).click();await m.screenshot({path:'/downloads/slice-evidence/master-closed.png',fullPage:true});await m.getByRole('button',{name:'Все наряды'}).click();await m.screenshot({path:'/downloads/slice-evidence/master-dashboard.png',fullPage:false});
const history=await(await master.request.get('http://127.0.0.1:5173/api/equipment-history?id=1')).json();assert.ok(history.orders.some(o=>o.id===id));const report=await(await master.request.get('http://127.0.0.1:5173/api/report?since='+encodeURIComponent(new Date(Date.now()-3600000).toISOString()))).json();assert.ok(report.rows.every(o=>new Date(o.created_at)>=new Date(Date.now()-3605000)));results.push('Equipment history and date-filtered report readback verified');state=await(await master.request.get('http://127.0.0.1:5173/api/state')).json();const record=state.orders.find(o=>o.id===id);assert.equal(record.status,'closed');assert.equal(record.ai_result.mode,'rules');assert.equal(record.ai_result.confidence,null);assert.equal(record.ai_result.human_score,4);assert.equal(record.closure.photo_evidence[0].sha256.length,64);assert.ok(record.closure.photo_evidence[0].byte_size>0);assert.equal(state.events.filter(e=>e.order_id===id).length,6);results.push('Database readback: closed, six immutable audit events, no fabricated AI confidence');
const lp=await leader.newPage();await lp.goto('http://127.0.0.1:5173');await lp.getByRole('button',{name:'Руководитель Руководитель'}).click();await lp.getByRole('heading',{name:'Наряды смены'}).waitFor();await lp.getByRole('button',{name:'Отчёт и рейтинг'}).click();await lp.locator('.report h2').waitFor();await lp.locator('.report').evaluate(el=>el.scrollIntoView({block:'start'}));await lp.waitForTimeout(400);await lp.screenshot({path:'/downloads/slice-evidence/manager-report.png',fullPage:false});await lp.pdf({path:'/downloads/slice-evidence/manager-report.pdf',format:'A4',printBackground:true});await m.getByRole('button',{name:'Канбан',exact:true}).click();await m.locator('.kanban').waitFor();await m.screenshot({path:'/downloads/slice-evidence/master-kanban.png',fullPage:false});
writeFileSync('docs/vertical-slice-results.json',JSON.stringify({verified_at:new Date().toISOString(),tests:results,realtime_local_ms:realtimeMs,limits:['Only local PostgreSQL, no Supabase deployment','Demo account chooser, not production auth','Rules-only review, no Gemini','Synthetic photo does not prove a repair','No Android physical-device checks yet']},null,2));console.log(JSON.stringify(results,null,2));
}catch(e){console.error(e);if(browser){for(const ctx of browser.contexts()){for(const page of ctx.pages()){try{await page.screenshot({path:'/downloads/slice-evidence/debug-'+Math.random().toString(36).slice(2)+'.png'});console.log('FAILPAGE',await page.locator('body').innerText())}catch(debugError){console.error('Failure evidence capture failed',debugError.message)}}}}process.exitCode=1}finally{if(browser)await browser.close();for(const p of children.reverse()){p.kill('SIGTERM');await Promise.race([new Promise(r=>p.once('exit',r)),wait(2500)])}await wait(200)}
