// Isolated synthetic truth, NOT production seed, failure prediction or factory instructions.
export const demoKnowledge=[
{id:'SYN-1',title:'Конвейер К-3 (Т): повтор М-02',source:'Синтетический учебный кейс, не заводской норматив',text:'Повтор кода М-02 на одном узле после закрытия. Рекомендация мастеру: сверить историю и документацию привода; причина не установлена.'},
{id:'SYN-2',title:'Дробилка КМД-1750 (Т): после плановой работы',source:'Синтетический учебный кейс, не заводской норматив',text:'Внеплановый наряд в течение 48 часов после планового. Это последовательность, не доказательство плохого ремонта; мастер проверяет связь.'},
{id:'SYN-3',title:'Насос Н-12 (Т): расход материала',source:'Синтетический учебный кейс, не заводской норматив',text:'80 единиц при типовом синтетическом расходе 2. Сверить единицы и документ списания. Порог не является заводским нормативом.'},
{id:'SYN-4',title:'Насос Н-12 (Т): фото отсутствует',source:'Синтетический учебный кейс, не заводской норматив',text:'Короткая причина: «Нет фото». Доработка обязательного отчёта не означает установленный дефект ремонта.'}
];
export function syntheticHistory(){let id=1;const orders=[];const add=(equipment,day,hour,fault='М-02',kind='unplanned',material=2)=>orders.push({id:'SYN-'+id++,title:equipment+' · учебная запись (Т)',equipment,created_at:new Date(Date.UTC(2026,6,8+day,hour)).toISOString(),kind,fault,material_quantity:material,synthetic:true,include_in_live_rating:false});
for(let day=0;day<90;day++){add('Конвейер К-3 (Т)',day,8);add('Конвейер К-3 (Т)',day,12);add('Конвейер К-3 (Т)',day,16);add('Конвейер К-4 (Т)',day,10);add('Конвейер К-5 (Т)',day,10);if(day%7===0){add('Дробилка КМД-1750 (Т)',day,8,'М-03','planned');add('Дробилка КМД-1750 (Т)',day+1,8,'М-03')}add('Насос Н-12 (Т)',day,10,'М-04','unplanned',day===45?80:2)}
return orders}
export function detectSynthetic(orders){const n=name=>orders.filter(o=>o.equipment===name&&o.kind==='unplanned').length;const repeat=orders.filter(o=>o.equipment==='Конвейер К-3 (Т)'&&o.fault==='М-02').length;const ppr=orders.filter(o=>o.kind==='planned'&&orders.some(x=>x.equipment===o.equipment&&x.kind==='unplanned'&&Date.parse(x.created_at)>Date.parse(o.created_at)&&Date.parse(x.created_at)-Date.parse(o.created_at)<=48*3600000)).length;const high=orders.filter(o=>o.material_quantity>10).map(o=>o.id);return {frequency_ratio:n('Конвейер К-3 (Т)')/n('Конвейер К-4 (Т)'),same_code_count:repeat,post_planned_within48h:ppr,material_spikes:high}}
