import{chromium}from'@playwright/test';import assert from'node:assert/strict';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';
export async function runStage7Cycle({c,storage,endpoint}){
 const dir='/downloads/stage7';mkdirSync(dir,{recursive:true});const start=Date.now(),since=new Date(start-50).toISOString(),steps=[];const master='00000000-0000-4000-8000-000000000001',worker='00000000-0000-4000-8000-000000000002';
 const as=async(id)=>{await c.query('reset role');await c.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role','authenticated',false)",[id]);await c.query('set role authenticated')};
 const order=async(id)=>(await c.query('select * from orders where id=$1',[id])).rows[0];const event=async(id,status,reason='',closure=null)=>{const o=await order(id);await c.query('select transition_order($1::bigint,$2::text,$3,$4,$5,null,$4)',[id,status,o.version,reason,closure])};const record=name=>steps.push({name,ms:Date.now()-start});
 const issue=async(title)=>{await as(master);return Number((await c.query("insert into orders(title,kind,equipment_id,assignee_id,master_id,priority,deadline)values($1,'unplanned',1,$2,$3,'emergency',now()+interval '1 hour')returning id",[title,worker,master])).rows[0].id)};
 const required=['Подтверждаю лично: требования безопасности выполнены согласно утверждённой для этой задачи процедуре (включая обесточивание, заземление и LOTO, если они требуются процедурой)','Подтверждаю лично: использую средства защиты, зона работ безопасна'];
 const begin=async(id)=>{await as(worker);await event(id,'accepted');let o=await order(id);await c.query("select record_permit($1,'not_required','',$2)",[id,o.version]);await c.query('select start_work_with_declarations($1,$2,$3)',[id,o.version,required])};
 const finish=async(id)=>{await as(worker);const o=await order(id);await c.query('reset role');const r=await fetch(endpoint.replace(/4$/,String(id)),{method:'POST',headers:{authorization:'Bearer synthetic-worker-session','x-order-version':String(o.version)},body:readFileSync('tests/fixtures/canonical-after.jpg')});if(r.status!==201)throw Error(await r.text());const photo=await r.json();await as(worker);await event(id,'completed','',{works:'Повторная учебная замена уплотнения и проверка герметичности',fault_code:'T01',materials:[],photos:[photo.canonical]})};
 const api=async(path,body)=>{const r=await fetch(endpoint.replace('/api/canonical-photo/4',path),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,role:'master'})});if(!r.ok)throw Error(await r.text());return r.json()};
 // No fixed status seeds: new orders each follow versioned transitions and original-byte ingest.
 const first=await issue('Stage7 emergency primary');await begin(first);record('1-issued-accepted-started');
 const second=await issue('Stage7 queued second');await as(worker);await event(second,'queued');await event(second,'accepted');let o=await order(second);await c.query("select record_permit($1,'not_required','',$2)",[second,o.version]);await assert.rejects(c.query('select start_work_with_declarations($1,$2,$3)',[second,o.version,required]),/already has/);assert.equal((await order(second)).status,'accepted');record('2-queued-second-parallel-start-denied');
 await as(master);await event(first,'paused','Синтетическое диспетчерское переключение');await as(worker);await c.query('select start_work_with_declarations($1,$2,$3)',[second,(await order(second)).version,required]);await api('/app-fixture-overdue',{id:second});await c.query('reset role');const notifications=(await c.query("select * from notifications where order_id=$1 and kind='overdue'",[second])).rows;assert.ok(notifications.some(n=>n.recipient_id===worker)&&notifications.some(n=>n.recipient_id===master));record('3-overdue-durable-two-recipient-dispatch');
 await finish(second);record('4-report-canonical-completed');await api('/app-review',{id:second,version:(await order(second)).version});let reviewed=await order(second);assert.equal(reviewed.status,'ai_review');assert.ok(reviewed.ai_result.evidence_guards.photo);assert.ok(!reviewed.ai_result.evidence_guards.photo.flags.includes('server_pixel_decode_unavailable'));assert.equal(reviewed.ai_result.score,null);record('5-server-stored-pixel-review-archived');
 await as(master);await event(second,'rework','Учебная проверка мастера: дополнить контроль');await as(worker);await event(second,'in_progress');await finish(second);await api('/app-review',{id:second,version:(await order(second)).version});await as(master);const before=(await order(second));await c.query("select transition_order($1::bigint,'closed'::text,$2,'Ручная оценка',null,4,'Проверил лично')",[second,before.version]);record('6-reviewed-rework-resubmit-review-human-close');
 // Close original after second. Repeat is a signal on same equipment/fault within7days, not causal blame.
 await as(worker);await event(first,'in_progress');await finish(first);await api('/app-review',{id:first,version:(await order(first)).version});await as(master);await c.query("select transition_order($1::bigint,'closed'::text,$2,'Ручная оценка',null,5,'Проверил лично')",[first,(await order(first)).version]);
 const repeat=await issue('Stage7 repeat same fault');await begin(repeat);await finish(repeat);await api('/app-review',{id:repeat,version:(await order(repeat)).version});await as(master);await c.query("select transition_order($1::bigint,'closed'::text,$2,'Ручная оценка',null,4,'Проверил лично')",[repeat,(await order(repeat)).version]);
 const refused=await issue('Stage7 refusal reviewed');await as(worker);await event(refused,'rejected','other: учебный спорный отказ');await c.query('reset role');const refusal=(await c.query("select id from order_events where order_id=$1 and new_status='rejected'",[refused])).rows[0];await as(worker);await assert.rejects(c.query("select review_refusal($1,'justified','Тест')",[refusal.id]));await as(master);await c.query("select review_refusal($1,'justified','Учебное подтверждение отсутствия допуска')",[refusal.id]);record('7-repeat-and-reviewed-refusal-audit');
 const until=new Date(Date.now()+1000).toISOString();const ratings=(await c.query('select * from worker_rating($1,$2)',[since,until])).rows;assert.equal(ratings.length,1);assert.equal(ratings[0].factors_available,5);assert.ok(Number(ratings[0].rework)>=2);assert.equal(Number(ratings[0].rejects_justified),1);assert.equal(Number(ratings[0].quality_n),3);writeFileSync(dir+'/runtime-ratings.json',JSON.stringify({since,until,ratings,synthetic:true},null,2));record('8-five-factor-runtime-rating');
 const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:390,height:844},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5198/orders/'+second+'?role=master');await page.getByText('Окончательное решение мастера: закрыт',{exact:true}).waitFor();await page.locator('.final-master-decision').scrollIntoViewIfNeeded();await page.screenshot({path:dir+'/reviewed-rework-final.png'});await page.goto('http://127.0.0.1:5198/handover?role=master');await page.getByText('Сводка для передачи смены',{exact:true}).waitFor();await page.getByText('Сводка для передачи смены',{exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:dir+'/shift-summary.png'});
 // Actual runtime RPC scoped from stage7start then same native exporters, not fabricated ratings.
 for(const format of['xlsx','pdf']){const dl=page.waitForEvent('download');await page.evaluate(async({since,until,format})=>{const H=await import('/src/lib/data.ts'),{ratingDoc}=await import('/src/lib/report-docs.ts'),{downloadBytes}=await import('/src/lib/report-download.ts');const rows=await H.ratings(since,until);const doc=ratingDoc(rows,{since,until});if(format==='xlsx'){const{buildXlsx,sheetsFromDoc}=await import('/src/lib/xlsx-writer.ts');downloadBytes('stage7-runtime-rating.xlsx',buildXlsx(sheetsFromDoc(doc)),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}else{const{loadReportFonts}=await import('/src/lib/report-font.ts'),{reportDocToPdf}=await import('/src/lib/report-pdf.ts');downloadBytes('stage7-runtime-rating.pdf',reportDocToPdf(doc,await loadReportFonts()),'application/pdf')}},{since,until,format});await(await dl).saveAs(dir+'/runtime-rating.'+format)}
 for(const route of['/settings','/assistant','/orders','/profile','/unknown-stage7']){await page.goto('http://127.0.0.1:5198'+route+'?role=worker');await page.locator('nav').waitFor();assert.equal(await page.locator('button:focus').count(),0);await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.activeElement!==document.body));}await page.addInitScript(()=>{window.__rec=[];window.__ask=[];class R{constructor(){window.__rec.push(this)}start(){this.onstart?.()}stop(){this.onend?.()}abort(){}}window.SpeechRecognition=R});await page.goto('http://127.0.0.1:5198/tests/voice-browser/harness.html');const panel=page.locator('#askpanel');await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Начать голосовой вопрос'}).click();await page.evaluate(()=>{window.__rec.at(-1).onresult({results:[Object.assign([{transcript:'Учебный вопрос'}],{isFinal:true})]})});assert.equal(await page.evaluate(()=>window.__ask.length),0);assert.match(await panel.getByLabel('Вопрос текстом').inputValue(),/Учебный/);await panel.getByRole('button',{name:'Отправить вопрос'}).click();await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>window.__ask.length),1);await panel.getByRole('button',{name:'Начать голосовой вопрос'}).click();await page.evaluate(()=>window.__rec.at(-1).onerror({error:'not-allowed'}));await panel.getByLabel('Вопрос текстом').fill('Ручной текст после ошибки');assert.equal(await panel.getByLabel('Вопрос текстом').inputValue(),'Ручной текст после ошибки');await page.screenshot({path:dir+'/voice-error-draft.png'});assert.deepEqual(errors,[]);writeFileSync(dir+'/routes.json',JSON.stringify({routes:5,pageErrors:errors,scope:'Browser route/focus smoke, not complete accessibility audit'}));record('9-handover-exports-routes');}finally{await browser.close()}
 await c.query('reset role');const audit=(await c.query('select order_id,new_status,actor_id,reason,created_at from order_events where order_id=any($1::bigint[]) order by id',[[first,second,repeat,refused]])).rows;writeFileSync(dir+'/timing-and-audit.json',JSON.stringify({elapsed_ms:Date.now()-start,steps,audit,scope:'Local SQL RPC transactions + HTTP canonical/serverpixelreview + React final/handover/runtimeexport/routes. Not full9stepsbyUI, devicepush orhumanlatency. Syntheticdeadlinefixture.'},null,2));console.log('STAGE7 TRANSACTIONS 5/5RATING SERVERPIXEL REVIEW AUDIT EXPORTS ROUTES PASS',Date.now()-start);
}
